### ISSUE TITLE
authorship policy

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#10]
*What I wrote on the scipy-dev mailing list on Jan 20th*:
Authorship: anyone who made a substantial contribution in the history of the project. Here "substantial" is interpreted as anything beyond a one-line doc fix. Rationale: better to be too inclusive than exclusive. Sign-up via a web form, we send the link to that form to all email addresses in the commit history till v1.0.

Author order (details tbd by committee):
1. The SciPy Developers
2. Maintainers, paper writers, other key contributors - in order of contribution level
3. All other authors - alphabetically ordered

*Comment by Pauli*:
For the authorship policy, to my knowledge there's no established
standard what to do, and maybe the journal editors have an opinion, and
maybe we can look what other projects did. The contributor list to the
releases is likely 600+ people, many of those indeed typo fixes, and
probably don't exceed authorship threshold. If we want to do manual
pruning, we can in principle split the list to "Authors" (who did
something that when summarized in a single sentence sounds substantial)
and "Contributors" (the rest, who are thanked in the acknowledgements).
However, in some fields of physics, the author list tends to list
everyone and grow big, e.g. the experimental Higgs paper [1] has 5000+
authors, the author list is summarized to (XXX collaboration).

[1] https://dx.doi.org/10.1103/PhysRevLett.114.191803

For example, here's the Physical Review guidelines for authorship:

- The paper represents original work of the listed authors.
- All of the authors made significant contributions to the concept,
design, execution, or interpretation of the research study.
- All those who made significant contributions were offered the
opportunity to be listed as authors.
- All of the listed authors are aware of and agree to the submission of
this manuscript.

The last constraint I think is important and appears in most
guidelines. We probably don't have the current contact information for
many of the contributors, and it's likely we won't receive "sign off"
statements from several of them.

**Comment by rgommers** [comment]
> All of the listed authors are aware of and agree to the submission of this manuscript.
>
> The last constraint I think is important and appears in most
guidelines. We probably don't have the current contact information for
many of the contributors, and it's likely we won't receive "sign off"
statements from several of them.

I'd suggest that this one is not hard to meet:
- we design a web form and email everyone in the commit history. and announce it on the mailing list
- who does not reply doesn't make the author list
- we will make some special effort to contact current or former core devs who don't reply
- we will ignore the rule for people we know really should be on the paper (e.g. Travis O., Eric J. and Pearu P.). this is commonly done on papers, and the right thing to do in this case.

**Comment by rgommers** [comment]
What constitutes "significant contributions" is tricky. I'd be in favor of formulating it as "more than a simple doc typo fix" and leaving it up to people to decide whether they (a) clear that bar, and (b) clear a higher bar than that which they set for themselves. We then only check if they clear (a).

**Comment by rgommers** [comment]
@ev-br commented:  It might happen that we need to decide on a person having contributed significantly or not. I suggest we vote in [the coordination committee], with the deciding vote being the RM or BDFL.

**Comment by charris** [comment]
Might want to collect some statistics on reviewers, although I suspect most are also maintainers.

**Comment by mdhaber** [comment]
I've done a little digging into the GitHub API to see what information we can collect. It seems possible to generate a report, organized by GitHub user, on _all_ contributions to SciPy (including issue comments and PR reviews). It is also possible to get more recent email addresses than those used for a SciPy commit if the person has other, more recent, public activity on GitHub. Here's a thought:

- Collect all the information we think is important to determine authorship (if more than commits)
- Rank everyone with some sort of heuristic and apply some threshold to roughly determine who qualifies as an author
- Email everyone (at all available email addresses) informing them of the status. Those who didn't make the cut can appeal. Those who want to be listed need to agree to the manuscript.

This would be a bit of work, but it would be more comprehensive than relying solely on the commit history. In any case, just thought I'd mention the API's capabilities, as they weren't mentioned explicitly here before.

Thoughts?

--- 

Some relevant examples of API calls:

User public event log (for getting email addresses):
https://api.github.com/users/mdhaber/events/public
Commit list:
https://api.github.com/repos/scipy/scipy/commits
Specific commit: (could analyze diff to assess magnitude of contribution)
https://api.github.com/repos/scipy/scipy/commits/6a3fcee67c889ef12926afaad717407b378b9101
Issue list:
https://api.github.com/repos/scipy/scipy/issues
Specific Issue:
https://api.github.com/repos/scipy/scipy/issues/8747
Comments on Issue:
https://api.github.com/repos/scipy/scipy/issues/8745/comments
Reviews on PR:
https://api.github.com/repos/scipy/scipy/pulls/8295/reviews/
Comments on reviews on PR:
https://api.github.com/repos/scipy/scipy/pulls/8295/reviews/88699345/comments

Where applicable, results can be traversed using pagination e.g. 
https://api.github.com/repos/scipy/scipy/commits?page=2

**Comment by andyfaff** [comment]
> It seems possible to generate a report, organized by GitHub user, on all contributions to SciPy (including issue comments and PR reviews)

PR reviewing and digging to the bottom of issues are extremely valuable contributions, and it would be good to recognise that somehow. It's hard to judge though.

**Comment by mdhaber** [comment]
@andyfaff Certainly is hard to judge automatically, but not so hard for a human. So it would at least be good to collect the email addresses of issue/PR contributors and contact them so they have the opportunity to reply suggesting why they should be included (if they don't meet whatever initial automated criterion we set). Spread around, manual review of those who reply wouldn't be too bad.
Matt

**Comment by mdhaber** [comment]
Well I did it anyway.  Let me know if you have thoughts on how contributions should be assessed. (Sum of length of comments, reviews, review comments, and + lines on diffs?)

**Comment by rgommers** [comment]
Interesting. I'd think that the number of contributors with significant review activity but zero commits is close to or at zero, but if you've already done the work to extract the data then let's assess the results! 

For a rough ranking I'd suggest something like:
- one list of contributors, simply ordered by number of commits
- another list of people with activity but no commits; ordered by number of review comments, and if you're having fun and want to add a tie-breaker, use the sum of length of comments.

**Comment by mdhaber** [comment]
@rgommers Note quite zero : ) But close. Depends on how we define "significant".
Looks like it might be helpful, though. For instance, @metaperature's contribution to #7630 would not have shown on the commit list, but he is near the top of the PR review list.  There are a few others I'll let others assess. Should I push this data to the repo? (Maybe I should remove real names and email addresses to the version I push, though?)

**Comment by rgommers** [comment]
I'd say no - better to keep the data private. It's only for use by the paper organizers to sanity check the author list and make decisions on who should be on it in case of doubt. And the method of ranking isn't reviewed or even thought about very hard, it's just for us.

**Comment by stefanv** [comment]
FWIW, we now gather review statistics during scikit-image releases.  Perhaps the tool we wrote for that purpose is also useful here in identifying reviewers:

https://github.com/kne42/scikit-image/blob/53753269e3501acb5bf21c6e0edf1df85b2daaba/doc/release/contribs.py (PR is about to be merged: https://github.com/scikit-image/scikit-image/pull/2927)

**Comment by mdhaber** [comment]
Thanks @stefanv, but since I hadn't heard back, I wrote something similar in April. It downloads pertinent information from all commits, issues, issue comments, PRs, PR reviews, and PR review comments. We  could use the scikit-image one to check accuracy and completeness of mine for some of those, but I think mine is working pretty well. (Exposed bugs in the GitHub API while writing it though, which is why I'm not 100% confident.)

**Comment by mdhaber** [comment]
Author decisions complete.
