### ISSUE TITLE
Timeline Graphic?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#107]
I think Figure 2 should be represented graphically or eliminated.

![scipy_timeline](https://user-images.githubusercontent.com/6570539/53224731-93efbf80-362a-11e9-9556-dd0198e893b9.png)

Getting permission to print logos might be a headache. I suppose we could just lay out the text on a timeline? Anyway, I'm suggesting something other than the current text list.

**Comment by rgommers** [comment]
Oh pretty! Logo permissions for Github and TravisCI could be nontrivial, the rest will be fine

**Comment by ilayn** [comment]
https://github.com/logos

GitHub seems also fine.

**Comment by mdhaber** [comment]
And I had seen Travis' policy while getting there logo.
https://travis-ci.com/logo
They say it's ok. But do we have to include the wordmark with it? I couldn't tell.

**Comment by mdhaber** [comment]
Does anyone have a better version (preferably vector) of the SciPy logo? Is red correct for library and blue for community? 

I didn't think much about the events to include from the original list. Let me know what needs in and out.

**Comment by rgommers** [comment]
> Does anyone have a better version (preferably vector) of the SciPy logo? 

I don't, unfortunately

> Is red correct for library and blue for community?

yes. it hasn't always been consistent, but this sounds right to me

**Comment by mdhaber** [comment]
@ilayn @rgommers Thanks; I'd appreciate your thoughts about the latest version of this graphic in #108.
