### ISSUE TITLE
design web form author info and invite co-authors

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#11]
No action yet, to be done after we have decided on authorship policy and have a first draft of the paper ready.

**Comment by mdhaber** [comment]
What information needs to be on this form other than:

- Name, as it should be listed in the paper
- Preferred email address (if different from how we contacted them)
- Other names / usernames that belong to the same person (if applicable)

Often workplace information is included on papers but is that important for such a long, global list?

I would be happy to make this if a Google form is sufficient.

**Comment by ev-br** [comment]
Yes, affiliation(s) are needed, some people may need to include several.

**Comment by mdhaber** [comment]
Here is a draft of the email to be sent to _every_ email address associated with activity on the SciPy GitHub repo. Some questions:

- Is the criterion for inclusion (adopted from @rgommers on #10) appropriately stated? Especially, are we looking for at least one `substantial contribution` as stated or would a long history of trivial contributions be considered `substantial`?
- Is this the right approach for evaluating whether that criterion is satisfied, namely asking everyone interested to justify how at least one of their contributions satisfies it? On the form, perhaps we'd ask them to provide a link to the relevant PR or directly to their review or commit.
- Should we include the summary of activity collected from GitHub at the end? I think it would help remind people what they've done so they can choose a contribution to write about in the form.
- Is the author order (adopted form @pv on #10) interpreted correctly? 
- Do we want submission of the form to constitute "awareness of and agreement to the submission of the manuscript", or should there be a separate form for that later when we are sending a final draft?
- Is the tone right? I'm afraid it is not as welcoming as the draft from the Astropy project it is based one.
- @rgommers is it different enough from the Astropy email?

> Dear SciPy Contributor*,
> 
> We have drafted a paper (to be submitted to Nature Publishing Group's Scientific Reports) to document the release of SciPy 1.0. The purpose of this email is to invite everyone who has made at least one 'substantial' contribution to the project to be an author. 
> 
> One proposed definition for 'substantial' is 'anything beyond a one-line doc fix', however ultimately decisions regarding the author list will be subjective. To streamline the decision process, we ask that you fill out the following (short) form if you believe you have made a 'substantial' contribution and wish to be considered for inclusion on the author list.
> <url>
> 
> The form asks you to record affiliation(s) to be listed on the paper and briefly justify why at least one of your contributions (summarized in the postscript) is 'substantial'. You will also certify that you are aware of and agree to the submission of the manuscript, and that if selected as an author you will read the final draft of the paper and take appropriate action if you disagree with any content.
> 
> The coordination committee has determined that the author order will be 'The SciPy Developers' as first author; maintainers, paper writers, and other key contributors in order of contribution level; and all other authors in alphabetical order. A footnote in the paper will document how the author order was determined. Final decisions about author order will be made by the paper coordination committee with a deciding vote, if needed, provided by the Release Manager (Ralf Gommers) or Benevolent Dictator for Life (Pauli Virtanen).
> 
> Once authorship decisions are made, those who submitted the form above will receive an email with their status and a link to a final draft of the paper. 
> 
> Please feel free to contact me or Ralf Gommers (cc'd) if you have any questions or comments. Thanks to everyone for your contributions to SciPy!
> 
> Matt Haberland (on behalf of the paper coordination committee)
> 
> * Your email was identified as being associated with a GitHub account that made at least commit, issue, pull request, review, or comment at the SciPy main repository. Thank you for understanding if you receive this email in error and/or if you receive duplicates; we may have erred on the side of being overly-inclusive!
> 
> P.S. Here is a summary of your SciPy activity we found on GitHub. Please let us know if there are any errors or omissions.

**Comment by rgommers** [comment]
> One proposed definition for 'substantial' is 'anything beyond a one-line doc fix', however ultimately decisions regarding the author list will be subjective.

That definition was mine, however I think @pv proposed a slightly higher threshold, which I'm fine with (authorship for two one-liners is quite inclusive). How about:
*Our definition of 'substantial' is "one new feature or significant improvement (e.g. performance or accuracy improvement) to an existing feature, or multiple smaller contributions.*

> Is this the right approach for evaluating whether that criterion is satisfied, namely asking everyone interested to justify how at least one of their contributions satisfies it? On the form, perhaps we'd ask them to provide a link to the relevant PR or directly to their review or commit

It's probably not needed for people to list their PRs, since we already have the list of contributions. I suggest to leave it out.

> Should we include the summary of activity collected from GitHub at the end?

Sounds useful to me.

> Is the author order (adopted form @pv on #10) interpreted correctly?

yes 

> Do we want submission of the form to constitute "awareness of and agreement to the submission of the manuscript", or should there be a separate form for that later when we are sending a final draft?

I think it's better to have it in a single form.

> Is the tone right? I'm afraid it is not as welcoming as the draft from the Astropy project it is based one.

I think it's not too bad; it can probably be improved a bit by tweaking the first paragraph. Maybe something like: *We're delighted to tell you that we have a paper about SciPy 1.0 in preparation, and we're contacting you as a potential co-author on that paper. We appreciate all contributions made to SciPy over the past 17 years, and are aiming to include everyone who has made a significant contribution to SciPy over that period on the paper. ...*

**Comment by mdhaber** [comment]
All sounds good except for:

>>Is this the right approach for evaluating whether that criterion is satisfied, namely asking everyone interested to justify how at least one of their contributions satisfies it? On the form, perhaps we'd ask them to provide a link to the relevant PR or directly to their review or commit

>It's probably not needed for people to list their PRs, since we already have the list of contributions. I suggest to leave it out.

For many people it will be obvious why they should be included, and in these cases, you're right, we don't really need them to justify their inclusion as an author.

For others, some commentary (not just a regurgitation of the list we send to them) highlighting their most significant contribution(s) will be helpful. Since there may be hundreds of authors, I think it is reasonable to place a little bit of the burden on the authors to justify their inclusion (and have the reviewers verify) rather than leaving it all to the few reviewers to figure out why each author should be included. I also think this slight "barrier to entry" will help to discourage those who really should not be included as an author.

Does that make more sense?

**Comment by rgommers** [comment]
Yes that make sense. So maybe a slight tweak to your text, to ask something like "if you're in doubt about whether your contributions qualify as significant, please tell us ...." - so it's clear for e.g. past maintainers that they don't have to do this.

**Comment by mdhaber** [comment]
OK. I think that I will leave this part out of the email and just include an optional box on the form. Draft 2:

> Dear SciPy Contributor*,
> 
> We're delighted to tell you that we have a paper about SciPy 1.0 in preparation, and we're contacting you as a potential co-author on that paper. We appreciate all contributions made to SciPy over the past 17 years, and are aiming to credit everyone who has made a significant contribution to SciPy over that period in the paper. 
> 
> Our definition for 'substantial' is "one new feature, significant improvement (e.g. performance or accuracy) to an existing feature, or multiple smaller contributions". However, ultimately decisions regarding the author list will be subjective. To streamline the decision process, we ask that you fill out the following (short) form if you believe you have made a 'substantial' contribution and wish to be considered for inclusion on the author list.
> 
> [SciPy 1.0 Paper Author Form](https://docs.google.com/forms/d/e/1FAIpQLScApdlW3PvJBhdXvSzzpJ54oAxUnZTNqD8tYpxZVv4G0jkQHQ/viewform?usp=pp_url)
>
> The form asks you to record affiliation(s) to be listed on the paper. You will also certify that you are aware of and agree to the submission of the manuscript, and that if selected as an author you will read the final draft of the paper and take appropriate action if you disagree with any content.
> 
> The coordination committee has determined that the author order will be 'The SciPy Developers' as first author; maintainers, paper writers, and other key contributors in order of contribution level; and all other authors in alphabetical order. A footnote in the paper will document how the author order was determined. Final decisions about author order will be made by the paper coordination committee with a deciding vote, if needed, provided by the Release Manager (Ralf Gommers) or Benevolent Dictator for Life (Pauli Virtanen).
> 
> Once authorship decisions are made, those who submitted the form above will receive an email with their status and a link to a final draft of the paper.
> 
> Please feel free to contact me or Ralf Gommers (cc'd) if you have any questions or comments. Thanks to everyone for your contributions to SciPy!
> 
> Matt Haberland (on behalf of the paper coordination committee)
> 
> * Your email was identified as being associated with a GitHub account that made at least commit, issue, pull request, review, or comment at the SciPy main repository. Thank you for understanding if you receive this email in error and/or if you receive duplicates; we may have erred on the side of being overly-inclusive!
> 
> P.S. Here is a summary of your SciPy activity we found on GitHub. Please let us know if there are any omissions or other errors.

**Comment by rgommers** [comment]
The email text looks good to me as is. I'd suggest waiting with sending it until we have a complete draft.

**Comment by pv** [comment]
Yes, I think we will want to have at least an initial "complete" draft.

**Comment by stefanv** [comment]
The email looks good to me (thanks!) except that I'd recommend you decide beforehand who will cast the vote (it currently states Ralf *or* Pauli); you can also change it to "Ralf *and* Pauli".

**Comment by mdhaber** [comment]
I wrote Ralf or Pauli based on what was in previous discussions, but agree it should be finalized. @rgommers , @pv Decision on this?

**Comment by rgommers** [comment]
I'm happy for Pauli to do it if he wants, and comfortable to do it otherwise. @pv your call.

**Comment by tylerjereddy** [comment]
Just checking in here:

- how far do we think we are from author invite stage? one thing @stefanv reminded me of is that when the invites happen there may be an influx of additional content change requests

**Comment by mdhaber** [comment]
I want to finish reviewing the last few sections of the paper (hopefully this weekend). There are a few sections at the end that need to be completed, and we need an abstract. Finally, we should get the figures in a representative (if not polished) state. The invitation list, invitation email, and web form are done.

**Comment by tylerjereddy** [comment]
We already have an abstract that people were happy with

**Comment by mdhaber** [comment]
Oops, my mistake.

**Comment by mdhaber** [comment]
Emails sent last week. 
Still waiting to hear whether it's OK to mention in a new issue all 3000 GitHub contributors in order to call their attention to the [Author Form](https://forms.gle/oh7LcU67Sq3VfEbDA).

**Comment by rgommers** [comment]
> Still waiting to hear whether it's OK to mention in a new issue all 3000 GitHub contributors in order to call their attention to the Author Form.

Ah I see I forgot to reply to the second email about that, sorry. I think it's going to be too spammy. For one I still don't get the 3000 - the main SciPy repo currently has 729 contributors only. Many of those, including most potential authors, we've already reached. I'd prefer to just ping the ones with invalid email addresses (like `@metaperture`) in the commit history.

**Comment by mdhaber** [comment]
> (like @metaperture) in the commit history.
@metaperture is not in the commit history at all. That was the point. I caught @metaperture's contribution by sheer luck, if I remember correctly. There may be others like @metaperture who contributed code but appear in the commit history at all, and that's why I suggested mentioning all 3000. 

> I'd prefer to just ping the ones with invalid email addresses 
Does that mean only the ones with improperly formatted email addresses or @no-reply.github.com? 
What about the 100+ email addresses returned to sender? (Note: it's time consuming to manually look through the returned messages, and it would still miss the people who don't use their commit email address anymore. )

**Comment by andyfaff** [comment]
We've done a large part of our due diligence by sending notifications to both scipy-dev and scipy-users.

**Comment by mdhaber** [comment]
@andyfaff True and GitHub finally replied: mentioning everyone in a single comment wouldn't work.

>Sorry for the delay in replying here. We have been looking into ways that this might work, but I'm afraid that it probably won't.
>- @-mentions are limited to 50 per comment. You can add more names in, but they won't be notified.
>- @-mentioning that many people would often result in you/ your project being reported by tagged users under our "report abuse" mechanism if they don't remember or aren't interested in being further involved in your project.
>- At GitHub, we operate on the assumption that people who want to be contacted will make that easy, and some people may well have publicly available email addresses on their profiles that you can use. 

>Others may have decided to watch the repository and will be notified of new issues automatically anyway.

Closing.

**Comment by jni** [comment]
@mdhaber do you still have the script to crawl the git history / github comments and email contributors? We are doing this for another project and it would be really nice to have something to start with! #FOSS ;) Thank you!

**Comment by mdhaber** [comment]
Oops, thanks for your patience @jni. I'll reply by email.
