### ISSUE TITLE
SciPy Begins Issue

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#112]
There were a few issues in the SciPy Begins section not fixed by #105:
- [ ] There are a lot of uncited facts in this section. Is that OK?
- [x] There are a ton of names mentioned in this section. Do we want that?
- [x] The paragraph beginning "As SciPy, the algorithms library of the ecosystem..." gives context to SciPy, but isn't really about the SciPy library. Does it deserve so much space?

**Comment by rgommers** [comment]
> There are a lot of uncited facts in this section. Is that OK?

facts look fine to me, however all software (e.g. ODEPACK, QUADPACK, and MINPACK) needs citing I think

> There are a ton of names mentioned in this section. Do we want that?

fine with me. a journal may frown upon it, but if so we can fix it at that point.

> The paragraph beginning "As SciPy, the algorithms library of the ecosystem..." gives context to SciPy, but isn't really about the SciPy library. Does it deserve so much space?

It's interesting to me, but yeah you could argue that it needs removing. I don't mind keeping it for now as the context is helpful. 

pinging @jarrodmillman too as he wrote this section

**Comment by mdhaber** [comment]
It's definitely interesting and I hope we can keep it. Hopefully there is space.

**Comment by jarrodmillman** [comment]
I would like to see it retained, but I am OK with it being removed.  For years, I've wanted to see this stuff documented somewhere and this seemed a natural spot.  If it seems to out of scope for others, I understand.

The article is getting a bit long and may exceed page limits.  However, I suspect this may be possible to get around.  The last article I wrote (https://www.frontiersin.org/articles/10.3389/fnins.2018.00727/full) was over twice as long as the official limit, but I was able to get an exception to the limit.  Unless folks feel there is a lot of material that should be removed, I think (if necessary) it would be worth trying to get a length exception for this paper as well.

**Comment by rgommers** [comment]
I feel the same way - we could also talk to the journal beforehand. I'd rather have the full article a lower-ranked journal (as long as it's indexed) than a half length article with all the "non-scientific" bits cut out.

**Comment by tylerjereddy** [comment]
Ok, the only action item here is to add a few more citations for some of the libraries we wrap I think. Note that some of those citations may already be available from later in the manuscript as well.

If we're still going with *Scientific Reports* for first try I anticipate that our editorial contact, Syma Khalid, will be fair.

**Comment by mdhaber** [comment]
I'm adding these citations
