### ISSUE TITLE
conda download stats

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#124]
Looks like we can now access conda download stats: https://github.com/ContinuumIO/anaconda-package-data

We hardly need more content, but may be fused the with PyPI numbers we have.

**Comment by rgommers** [comment]
yeah I saw that, it's pretty cool. having the code for easily extracting the numbers will be useful for many other things as well

**Comment by mdhaber** [comment]
I'll implement this.

**Comment by mdhaber** [comment]
Following the example from [`anaconda_package_data_example.ipynb`](https://github.com/ContinuumIO/anaconda-package-data/blob/master/anaconda_package_data_example.ipynb):
```
import intake
downloads = {}
for year in range(2017, 2019):
    downloads[year] = []
    for month in range(1,13):
        df = intake.cat.anaconda_package_data_by_month(year=year, month=month).to_dask()
        downloads[year].append(df.loc[(df.data_source=='anaconda') & (df.pkg_name=='scipy')]['counts'].sum().compute())
```
Crude, perhaps, but if it's correct, here's the Anaconda download data by year and month:
```
{2017: [336780, 451248, 564826, 455217, 448526, 475437, 495284, 545750, 456810, 549738, 503954, 492447], 
2018: [604374, 522963, 515439, 463161, 549805, 541555, 591086, 695490, 792380, 1109233, 914950, 763541]}
```
That's 5,776,017 in 2017 and 8,8063,977 in 2018.

**Comment by tylerjereddy** [comment]
Cool stuff, do you want to make a concise addition to the paper for those numbers? We should probably also keep those numbers handy for a cover letter that stands out.

**Comment by mdhaber** [comment]
There were 462,746 in 2017 and 1,724,744 om 2018 from the `conda-forge` channel.
