### ISSUE TITLE
M87 SciPy usage

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#126]
The recent excitement about black hole "imaging" from the M87 galaxy may also be leveraged with an appropriate citation of: https://iopscience.iop.org/article/10.3847/2041-8213/ab0c57/meta

SciPy / NumPy are directly cited there

**Comment by rgommers** [comment]
Cool. I like how they cited software at the end of the paper. Such a compact form makes it easier to be comprehensive in your citations.

**Comment by charris** [comment]
If you want to view the imaging code, it is on Github: https://github.com/achael/eht-imaging. It uses numpy matrices in some places, I suspect Python 3 was a later adaptation.
