### ISSUE TITLE
Possible repetition of facts about STScI in close proximity?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#139]
Right before the SciPy begins section:
"Initial work on numerical computing in Python was driven by graduate students, but soon larger research labs became increasingly engaged. For example, Paul Dubois at Lawrence Livermore National Laboratory (LLNL) took over the maintenance of Numeric and funded the writing of its manual[19], and in 1998 the Space Telescope Science Institute (STScI), which was in charge of Hubble Space Telescope science operations, decided to replace their custom scripting language with Python[20].

The third paragraph of SciPy begins:
"At this point, scientific Python started attracting more serious attention; code that started out as side projects by graduate students has grown into essential infrastructure at national laboratories and research institutes. For example, starting in 2000, STScI ported their IDL-based analysis pipeline, IRAF, to Python."

I can't tell whether the facts about the 1998 replacement of custom scripting language to the 2000 porting of the analysis pipeline are distinct. They are both prefaced with the idea that work started by graduate students become important at national labs, and they appear within half a page of one another, so I thought I should check.

In any case, I propose combining the two into the third paragraph of SciPy Begins. As I'm doing a "final" readthrough before release for wide review, I'm holding back my thoughts on erroneous commas etc., but I think this is important enough to bring up.

**Comment by rgommers** [comment]
Yes combining sounds good. This indeed feels like a duplicate. Even if it's not meant to be, one mention of STScI is enough.
