### ISSUE TITLE
Clean References

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#150]
The references section needs a fair amount of cleanup - stuff like sticking to capitalization and abbreviation conventions, adding access dates to URLs, etc.

**Comment by souravsingh** [comment]
I am interested in working on this. What do I need to do?

**Comment by mdhaber** [comment]
Great! That would be very helpful. Have you used LaTeX before?

**Comment by souravsingh** [comment]
Yes,I have used LaTeX before.

**Comment by mdhaber** [comment]
Great. Fork this repository, clone locally, and try to build `paper.tex` locally. I had to move some of the files that are in `scipy-1.0/static/` up to the root directory to get this to work for me. 

Once you have that working, you can edit `scipy-1.0/references.bib` to tweak the references until the format matches the [guidelines](https://www.nature.com/srep/publish/guidelines#references). 

For instance, reference 17 starts "Jim Hugunin", but the required style is "Hugunin, J.". The problem is that in the `.bib` file it is currently:
```
@online{Hugunin-first,
author = {{Jim Hugunin}},
title = {{The Matrix Object Proposal (very long)}},
year = 1995,
url = {https://mail.python.org/pipermail/matrix-sig/1995-August/000002.html},
urldate = {2019-1-15}
}
```
The double curly braces make it appear literally [as typed](https://tex.stackexchange.com/questions/294870/different-behavior-of-double-curly-braces-from-single-curly-braces-and-quotation) in the `.bib` file. Sometimes this is needed, but often you want BibTeX to be able to adjust capitalization, etc... So you would probably want to change it to:
```
@online{Hugunin-first,
author = {Hugunin, Jim},
title = {The Matrix Object Proposal (very long)},
year = 1995,
url = {https://mail.python.org/pipermail/matrix-sig/1995-August/000002.html},
urldate = {2019-1-15}
}
```
and BibTeX should be able to format it properly. If you notice that it is still not formatting properly, then we might have to adjust the bibliography style settings, but I think we are using the appropriate `.bst` file.

Does that make sense?

**Comment by mdhaber** [comment]
Thanks very much. This would be a big help.

**Comment by souravsingh** [comment]
Sure, I can work on this.

**Comment by mdhaber** [comment]
@souravsingh we'd like to submit the paper next week. Does that work for you?

**Comment by souravsingh** [comment]
Sure, I will check the manuscript and make any fixes needed.

**Comment by mdhaber** [comment]
Hey @souravsingh can you open a PR with what you have? We would really like to get this submitted as early as tomorrow.
