### ISSUE TITLE
Consider adding Debian popcon (popularity contest) statistic

### ISSUE THREAD

**Issue by yarikoptic** [scipy/scipy-articles#153]
ATM only the number of downloads from pypi and conda as an indicator of popularity.  But some could argue that they are very biased by all CI deployments and do not reflect actual user base installations.  Another additional statistic is Debian popularity contest which is voluntarily, opt-in, mechanism to report installed packages on the system.  The guestimate is that 1-10% of Debian users enable popcon submissions. What matters there is not the overall number of installations but the % of all Debian systems where scipy is installed.  ATM it seems to be somewhere above 4% systems: https://qa.debian.org/popcon.php?package=python-scipy

**Comment by mdhaber** [comment]
This is a small number. If I wanted to make the point that SciPy is _not_ very popular, I would probably use that figure. So I don't think we can put this alongside the number of downloads from PyPI and `conda`; we should decide which we think better represents reality.

If several CIs download from `conda` or PyPI on every deployment, then at least we need to remove "by users" from:
"These numbers establish a lower bound on the total number of downloads **by users**."

But these are substantial changes so I won't do either without more input from the group.

**Comment by mdhaber** [comment]
Does anyone know where our PyPI numbers for 2017 came from?
The paper says 13 million downloads from PyPI in 2017, and I'm seeing 10 million users last month alone:
https://pypistats.org/packages/scipy
Was there a 10x increase in download rate over the last year or could the difference be due to [this](https://pypistats.org/faqs#why-are-there-so-many-more-downloads-after-july-26-2018), in which case 13 million for 2017 was under-reporting?

**Comment by yarikoptic** [comment]
FWIW, given the popularity of debian and its derivatives, **4%** could easily reflect hundreds of thousands or even millions of installations.  But it is your call to either play this card or not.

**Comment by mdhaber** [comment]
@yarikoptic do you have a reference for the number of Debian users? I searched briefly but didn't find a number I thought I could use.

**Comment by tylerjereddy** [comment]
> Does anyone know where our PyPI numbers for 2017 came from?

I'm almost certain I cited the tool used to get those numbers--is it not in the manuscript now? It was some kind of open source database scraping tool @stefanv had showed me, I think.

**Comment by mdhaber** [comment]
There is a citation now. Not sure how I missed it (unless it was added after this). 

Anyway, there are again 10 million downloads last _month_ according to [PyPi Stats](https://pypistats.org/packages/scipy) but perhaps it is best to just stick with the 2017 number. It's an order of magnitude lower than what we're seeing now, so hopefully that abates concerns of CI inflation.

**Comment by stefanv** [comment]
@tylerjereddy Was it https://github.com/ofek/pypinfo?

**Comment by tylerjereddy** [comment]
@stefanv Yes, `git grep pypinfo` shows that exact citation in our master branch manuscript

**Comment by tylerjereddy** [comment]
In any case, yes it will be nice if we get more fine-grained & robust usage metrics in the future. Just like open source scientific libraries, the open source libraries used to generate their usage metrics can always be made better (& same for line coverage libraries.....).
