### ISSUE TITLE
Citation for paper "the astropy project" is shortened in a strange way

### ISSUE THREAD

**Issue by hamogu** [scipy/scipy-articles#157]
As of now, this is citation 141. The author as "The astropy Collaboration" as first author name. In the citation this is treated like a given name and shortened to "Collaboration, T. A." which does not make sense. It might be sufficient to replace the "and"s in the bibtex file for that entry with semi-colons. For example, how "linguist developers; the open source community" is formatted. On the other hand, I suspect that that's not journal style either and should be "linguist developers, open source community" with a , instead of ;.

Let me know if you want me to fiddle with the bibtex and turn this into a PR.

**Comment by mdhaber** [comment]
@souravsingh is working on the references (see #150), but maybe he could use some help?

You can probably fix this by putting {The Astropy Collaboration} in an extra set of curly braces.

**Comment by souravsingh** [comment]
I can look into this. I have successfully built the TeX files and I am now working on fixing the references.

**Comment by mdhaber** [comment]
Thanks, Sourav.

**Comment by mdhaber** [comment]
Added this to #150.
