### ISSUE TITLE
Table 1 too small?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#165]
https://www.nature.com/srep/publish/guidelines
"Unnecessary figures should be avoided: data presented in small tables or histograms, for instance, can generally be stated briefly in the text instead."
Should we bring this into the body of the text?

**Comment by mdhaber** [comment]
Could also just leave it and eliminate if they ask us to. I don't imagine it's a dealbreaker.

**Comment by apbard** [comment]
I would opt for leaving it. As you say, they will ask to remove it in case.

**Comment by mdhaber** [comment]
@WarrenWeckesser opinion?
One more to leave the table as-is and I'll close this issue.

**Comment by WarrenWeckesser** [comment]
Given that the content of the table could be expressed in a single sentence (e.g. something like "The code is SciPy is 50% Python, 25% Fortran, and 20% C, with the remainder including Cython, C++,  and other scripting languages and utilities"), I say take it out.

**Comment by mdhaber** [comment]
@tylerjreddy @ilayn @rgommers we seem to have conflicting opinions on this. Thoughts?

**Comment by ilayn** [comment]
I have very little preference on this. If the space permits table, otherwise inline is also fine

**Comment by mdhaber** [comment]
For consideration: #170.
