### ISSUE TITLE
Analysis of apparent conflict between linguist and pytest-cov/gcov data

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#171]
`linguist`'s report that SciPy 1.0 is ~50% Python / 50% Other appears to conflict with with Figure 3, which suggests that Python makes up much less of SciPy 1.0.

This discussion began in #99. It was attributed to (reasonable) differences in the way the respective tools generated the data. I started to take a closer look.

---
I used `linguist` with nearly default<sup>1</sup> settings to calculate the number of bytes of code in each language and with the `--breakdown` option to generate a list of all the files it counted. To see whether `linguist` is excluding important files, I cross-referenced this list with the list of all files in the SciPy directory (according to `os.walk`). Here are the extensions of all files that `linguist` did not count:
```
{'', '.example', '.conf', '.ini', '.md', '.py', '.css_t', '.sh', '.npy', '.npz', '.1', '.sample', '.mat', '.png', '.dat', '.scipy', '.idx', '.x', '.svg', '.css', '.README', '.arff', '.src', '.rst', '.less', '.0rc2', '.bat', '.yml', '.nc', '.in', '.toml', '.info', '.2', '.patch', '.0', '.mp3', '.ogg', '.pack', '.js', '.wav', '.json', '.0rc1', '.pyf', '.txt', '.sav', '.0b1', '.html'}
```
 
One of the hypothesized reasons for the apparent conflict was that `linguist` tries to exclude vendored code. This could make `linguist` under-count the amount of compiled code, and thereby over-count the relative amount of Python code. I don't recognize any of the extensions above to correspond with compiled code<sup>2</sup>, so I don't think that's happening.

The other hypothesized reason for the conflict was that `linguist` counts the amount of each language in terms of bytes whereas `pytest-cov` and `gcov` report the number of lines. I used the file list from `linguist` to count the number of lines in each file to get the number of lines in each language:
```
{'Python': 282567, 'Fortran': 162212, 'C': 131534, 'Cython': 20082, 'C++': 14231, 'TeX': 1479, 'Objective-C': 152, 'MATLAB': 181, 'Shell': 107, 'Makefile': 50}
```
Python files make up 46~47% of SciPy whether you're counting bytes or lines, so that's not it either.

I wondered whether blank lines and comments could be accounting for the difference, so I separately counted blank lines and lines beginning with `#':
```
{'Python': 215938, 'Fortran': 157945, 'C': 112317, 'Cython': 14902, 'C++': 11559, 'TeX': 1345, 'Objective-C': 135, 'MATLAB': 139, 'Shell': 86, 'Makefile': 29, 'Blank': 76765, 'Comments': 21435}
```
That helps.
I made a crude pass at counting docstrings separately by stopping the count when there is an odd number of `'''` or `"""` in a line:
```
{'Python': 141528, 'Fortran': 157945, 'C': 112317, 'Cython': 11257, 'C++': 11559, 'TeX': 1345, 'Objective-C': 135, 'MATLAB': 139, 'Shell': 86, 'Makefile': 29, 'Blank': 76765, 'Comments': 21435, 'Docstring': 78055}
```
That helps, too. 

But Figure 3 reports that the number of Python lines is only 106,878, which is still a lot less than the 141,528 I'm counting when I exclude Cython and try to remove comments, blank lines, and docstrings. 
It also reports that the number of compiled code lines is 462,574, which is still a lot more than the 330,028 I count when I include _everything_ (even blank lines, etc.) but Python. 
Clearly there is still something we're missing, and I'm getting less confident about the numbers shown in Figure 3.

Thoughts?

<sup>1</sup> By default, `linguist` counts all Python and Cython code as Python. I changed one setting: count `*.py` files as "Java".  Afterward, I changed the language labels (Python -> Cython, Java -> Python).
<sup>2</sup> The uncounted `.py` files are in the documentation, and there is a single uncounted `.sh` file.

**Comment by tylerjereddy** [comment]
I tried to analyze this in pretty gory detail in the linked PR already. I don't understand why my [Docker-based results / code](https://github.com/tylerjereddy/scipy-cov-track/blob/master/Dockerfile) aren't considered in more detail here. We cite them in the paper and for convenience here are sample gcov numbers associated with our manuscript: https://github.com/tylerjereddy/scipy-cov-track/blob/master/container_output/gcovr_details_v1.0.0.txt

For me, even a cursory glance at those gcov results, which total to the large 460k+ line count for compiled code mentioned above, includes various kinds of generated code and a bunch of stuff from the build directory for example.

There's nothing being hidden there--that's been completely open to improvement since code + sample results were published on Feb 20--if improvements are desired maybe open a PR to that repo and regenerate the data with more filters if needed, otherwise my suggested course of action is that the figure mostly remains as-is and if there are warts in the tools they are open source & can be improved moving forward.

At the very least, we consistently applied the same approach over the course of the project history for that figure. If the caption needs a modification for overly-inclusive gcov(r) line parsing that might be appropriate. If you want to try to filter out files that you "feel" aren't appropriate, that's fine by me, the code is open and maybe just propose / publish those modifications.

**Comment by mdhaber** [comment]
I haven't looked at those yet. That was the next step.

**Comment by ilayn** [comment]
We can also give both results and say somewhere in between. To be honest I don't trust both tools anyways.

**Comment by mdhaber** [comment]
@ilayn As you say, the percentage of SciPy that is Python code is probably somewhere between the 19% suggested by Figure 3 and the 50% reported by `linguist`, depending on how you count - and there is not just one way to count. We can certainly report both; but I want to understand why the numbers are so different.

**Comment by mdhaber** [comment]
OK now comparing the [container output](https://github.com/tylerjereddy/scipy-cov-track/tree/master/container_output) as Tyler suggested in #99:

- `linguist` looks at `tools` and `benchmarks`; `pytest` doesn't.
- `pytest` looks at `__init__.py` files within `/tests` folders; `linguist` doesn't.
- There are 22,676 lines in the files that `linguist` looks at that `pytest` doesn't.  
- Even after removing blank lines, comments, and docstrings, I count 129,486 lines in the files that `pytest` looks at - 22,608 more than `pytest` counts.

These differences more than account for the disagreement between `pytest` and `linguist` over the number of lines of Python code. 

Now I'll look at non-Python code.

**Comment by mdhaber** [comment]
As Tyler mentioned in this post, the number of lines of "compiled" code seems to be inflated by generated code - code not distributed with SciPy source but created during the build process.

For example, `/scipy/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/scipy/linalg/_flapackmodule.c` is not distributed with the SciPy source, and `gcov` reports 29,000 lines in the file alone.

Also, in `scipy/cluster/`, `gcov` counts 10,535 lines in `hierarchy.c`, 7,908 lines in `_optimal_leaf_ordering.c`, and 2,934 lines in `_vq.c`. The corresponding `.pyx` files have 1,175 lines, 501, and 369 lines respectively. 

@stefanv suggested in #99 that looking coverage of Cython-generated `.c` files would not be insightful. I agree that it's not the same as looking at coverage of `.pyx` files, but one could argue that looking at coverage of the `.c` files is actually what matters.

In any case, I think all of this analysis just leads to a short statement in the paper - probably in the caption of the test coverage data - that acknowledges the _apparent_ discrepancy and roughly explains that it is not the result of any mistakes. It's just different ways of looking at things, each of which is appropriate in its own context.
