### ISSUE TITLE
Cover Letter

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#174]
We need a [cover letter](https://www.nature.com/srep/publish/guidelines#cover-letter).

@tylerjereddy You've mentioned that you know our editorial contact, Syma Khalid. Did you plan on writing the cover letter or should I draft it? I was hoping we could submit by Wednesday.

**Comment by tylerjereddy** [comment]
Either way works for me--I'd suggest something concise that emphasizes how widely used SciPy is & how it doesn't have a proper paper yet.

Will Ralf or Pauli be the proper corresponding author? I can just ping Syma right before it is submitted as reminder that someone will be submitting.

**Comment by mdhaber** [comment]
It would be great if you could, then! The author list is going to take a bit of time as not everyone's submission is perfect.

**Comment by rgommers** [comment]
Could we have multiple corresponding authors? I think it was me tentatively, but happy to share:)

**Comment by mdhaber** [comment]
It's limited to three. 
https://www.nature.com/srep/journal-policies/editorial-policies#search-menu
I'd be happy to be one.

**Comment by rgommers** [comment]
Sounds good. You want to be the third @tylerjereddy ?

**Comment by tylerjereddy** [comment]
> You want to be the third @tylerjereddy ?

Sounds good -- I'll try to draft something
