### ISSUE TITLE
Complete Author List

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#175]
After authorship decisions are complete, we need to add the authors to the manuscript.

According to #10 the order is:
> 1. The SciPy Developers
> 2. Maintainers, paper writers, other key contributors - in order of contribution level
> 3. All other authors - alphabetically ordered

I think that means that 1 and 2 will be listed on the front page and 3 is the definition of the SciPy Developers consortium:
"In a separate section at the end of the manuscript (after the ‘References’ section) under the heading ‘Consortium’, the names of each consortium member should be listed."
https://www.nature.com/srep/journal-policies/editorial-policies#author-responsibilities

**Comment by rgommers** [comment]
That doesn't quite work. Since names of (2) cannot be included in (3), "The SciPy Developers" isn't the right name. It looks like like we should remove (1), first do (2) and at the end of (2) add "SciPy Contributors".

**Comment by mdhaber** [comment]
OK. Does this meet the intent?

1. Key maintainers and paper writers 
2. Other maintainers in alphabetical order
3. "SciPy Contributors Consortium"

Then the "SciPy Contributors Consortium" will be defined in a new "Consortia" section at the end of the paper, listing all other authors alphabetically.

**Comment by rgommers** [comment]
Close - not sure I know how to distinguish between "key maintainers" and "other maintainers" ....

How about simplifying to:

- Maintainers, paper writers, other key contributors, ordered by contribution level
- "SciPy Contributors Consortium", in alphabetical order

> Will there be an acknowledgments section for others who did not meet the criteria for authorship?

I'd suggest a generic "we thank all other contributors to SciPy ....". Impossible to name names.
