### ISSUE TITLE
Paper submission

### ISSUE THREAD

**Issue by apbard** [scipy/scipy-articles#185]
@mdhaber, @tylerjereddy, @rgommers  Has the paper already been submitted? Or otherwise, is there anything left still to be fixed?

**Comment by mdhaber** [comment]
The paper has been submitted. (I need to email everyone.) There are still things to be fixed like #150 and any other mistakes that might be found.

**Comment by stefanv** [comment]
Thank you for your hard work on this; much appreciated!

**Comment by tylerjereddy** [comment]
Scientific Reports Editorial Office is claiming it is out of scope as of last night, so we may need to think about other options.

**Comment by rgommers** [comment]
Too bad, not unexpected. I'd prefer to go to a journal that we know is going to be interested. Although @stefanv suggested Nature Methods, we could do a quick inquiry there. Otherwise just PeerJ or some other one that we know it's in scope for. The important thing is to publish it, journal reputation matters little for a paper with thousands of citations.

**Comment by antonior92** [comment]
I remember someone suggesting Plos One in some old thread. It is also a good alternative...

Also, have you considered putting the preprint in arXiv or some other preprint server? I think we definitely should consider it.

Finally, thank you Matt, Ralf, Tyler and others for pushing this paper forward. It reads really well now. Great work :)

**Comment by stefanv** [comment]
We should get in touch with the Nature Methods editor I connected with before submission, and at least ask her for advice given this feedback. She has the context, so is likely to be a helpful guide. Ralf and Tyler have her contact information.

**Comment by cbrueffer** [comment]
I agree with @antonior92 that having this out as a preprint would be good. This is especially important if it could end up behind a paywall (we had this situation with the Bioconda paper which is on bioRxiv and published in Nature Methods).

Thanks for the great work and inclusiveness everyone!

**Comment by andyfaff** [comment]
Sorry to hear about the knock back. I wonder if Nature Methods would work
then?

**Comment by ilayn** [comment]
This rejection/acceptance stuff brings back memories :) It is indeed unfortunate but still great piece of work. 

I agree with Ralf that journal won't matter much and it might be even slightly better to find an open journal to set an example. since publishing behind a paywall for an open source Python library would be hard to justify.

**Comment by stefanv** [comment]
I wouldn't consider this a rejection: they simply stated out of scope.

W.r.t. Ralf's comment of the journal not mattering, I am of two minds: yes, the paper will get cited a lot so SciP's value will be clear, but unfortunately the academic credit world is still broken enough that people take a lot of notice where you publish. So, there is perhaps some importance in terms of obtaining future grants or for individuals on the paper who need to check boxes to proceed up the academic ladder.

Anyway, if we played the credit or money games, we obviously wouldn't be here, so I support either route.

**Comment by tylerjereddy** [comment]
>  Although @stefanv suggested Nature Methods, we could do a quick inquiry there.

I sent an informal inquiry to Stefan's contact at *Nature Methods*, copying Matt, Ralf & Stefan. If they are willing to perform a "direct transfer" of the manuscript given the same parent publisher so we don't have to submit again that might be nice. Same goes for possibly waving part of their much larger open access costs if the paper is accepted.

Anyway, I brought up those points in the email.

**Comment by rgommers** [comment]
Thanks Tyler, that sounds good. Yes, avoiding having to reformat and retype all author info would be super useful.

**Comment by mdhaber** [comment]
That would be great. Note that I do generate the author list with a script, so if we do have to regenerate everything it's not the end of the world.
If you merge any PRs with author list corrections, please update the Google Sheet ("decisions", not original data).

**Comment by mdhaber** [comment]
The paper was submitted, so closing.
