### ISSUE TITLE
Decide on benchmark to show for ASV subsection

### ISSUE THREAD

**Issue by stsievert** [scipy/scipy-articles#19]
@tylerjereddy has drafted the ASV benchmark section in #15. In https://github.com/scipy/scipy-articles/pull/15#issuecomment-379328224, @tylerjereddy mentioned

>  I'll aim to merge on Sunday ... this doesn't mean that the asv section wont' still evolve or have a different final benchmark(s) in the end.

I think it's fine to merge that PR, but I would like to discuss which benchmark to display. Both @tylerjereddy and I have put in time to benchmark cKDTree and convolve respectively.

**Comment by stsievert** [comment]
I think we should consider what we want the benchmark to show. I think the main goal is to show ASV's capabilities, but I also think we should show

* that benchmarks improve with increasing versions
* that the benchmarks are practical

What else do we want to show?

**Comment by tylerjereddy** [comment]
@stsievert I went ahead with the merge since you were ok with it & there were no additional objections. Hopefully the section will continue to improve & what I've done could always be shifted to the supporting info over time.

**Comment by stsievert** [comment]
Thanks for merging it. Do you have any comments on the goals mentioned above?

**Comment by tylerjereddy** [comment]
Those are sensible goals -- I guess we can work on making our plots look as good as possible -- patching in those holes by running with 1 or 2 more versions of Cython for example.

We could also think about combining two different benchmarks in a single plot, though this may require i.e, custom code to work on the JSON if we want it to work nicely (and we may also simply prefer not to do a custom plot--since the default plots showcase the built-in plotting / comparison power of asv).

One thing I don't like about my contributed benchmarks is that you actually have to modify the source of the asv benchmark itself (not just the config file) to sample that far back in history.

I wonder if showcasing an example of `asv continuous` might also have some value -- to show that we can evaluate a single PR vs. the commit hash of the head of master -- this has occasionally been used in the past on isolated PRs to evaluate performance (though we often seem to accept i.e., informal benchmarks in a Jupyter nb as well...).

**Comment by stsievert** [comment]
> to show that we can evaluate a single PR vs. the commit hash of the head of master

That'd be a good idea show highlight a particular improvement, though the value added isn't clear to me. I would like to show some of ASV's web interface: I've found it useful already.

I think we could express the benefits of `asv continuous` in the figure caption or text, especially if a very sudden improvement shown ("The improvement shown in Figure X could also be shown with `asv continuous` which would produce a bar chart comparison between two commits or branches").

It'd also be nice to show the benchmark improving over time to show continual improvement, though I think that'd be harder in a benchmark with pinned versions/etc. Either way, the spatial.CNeighbors.time_count_neighbors_{deep, shallow} benchmarks improves over time, at least on https://pv.github.io/scipy-bench/.

Would it be fair to build the different scipy commits with different versions of the dependencies? I'm thinking to see how the scipy benchmarks have improved over time by including the latest version of it's dependencies the time of commit. Maybe we could do this by editing the config? This would be what the end user cares about I guess.

> One thing I don't like about my contributed benchmarks is that you actually have to modify the source of the asv benchmark itself (not just the config file) to sample that far back in history.

What code did you add?

**Comment by tylerjereddy** [comment]
> That'd be a good idea show highlight a particular improvement, though the value added isn't clear to me. 

The decision to accept / reject a PR might rest on a standard `asv continuous` for example. If you'd like to open a PR to add a small comment about it as you suggest that might be a good idea.

> Would it be fair to build the different scipy commits with different versions of the dependencies? 

As far as I know `asv` doesn't support this natively, as briefly discussed with @rgommers. We've both had gaps in our performance histories though, which can be closed by running with i.e., > 1 version of Cython, but that's not the same thing as using the version "associated" with the historical release for every single commit tested. That's probably something in the future for asv development, if people decide it makes sense.

> What code did you add?
```diff
diff --git a/benchmarks/benchmarks/spatial.py b/benchmarks/benchmarks/spatial.py
index d3cba5e..6c7fbb7 100644
--- a/benchmarks/benchmarks/spatial.py
+++ b/benchmarks/benchmarks/spatial.py
@@ -76,7 +76,7 @@ class Query(Benchmark):
         self.data = np.random.uniform(size=(n, m))
         self.queries = np.random.uniform(size=(r, m))
 
-        self.T = cKDTree(self.data, leafsize=leafsize, boxsize=boxsize)
+        self.T = cKDTree(self.data, leafsize=leafsize)

```

**Comment by stsievert** [comment]
> using the version "associated" with the historical release for every single commit tested. That's probably something in the future for asv development, if people decide it makes sense.

I'd like to see that. I think it'd be most useful to have two options: one option for fixed versions to show performance of only scipy, and another to enable different versions to see performance over time. But I imagine that'd be a lot of build work, and am unsure how difficult it is to implement.

I think we want to show continuous improvement, especially since `asv continuous` is mentioned. Given ASV's status, I'm inclined to find a benchmark that improves over time. I think cKDTree is suitable for this.

[1]:https://pv.github.io/scipy-bench/#sparse.Iteration.time_iteration?p-density=0.05&p-density=0.01&p-format='csr'&p-format='lil'&y-axis=log

**Comment by tylerjereddy** [comment]
On the topic of filling in the remaining (failing) benchmarks in the middle of the historical analyses -- I note that the gap is around scipy `0.12.0rc1`, near commit hash `4fe03a73ec55`. This commit hash is indeed probed by my most recent benchmark run, and `asv` reports a failure with no apparent error / traceback.

So, perhaps checking that in i.e., a docker container might help resolve the mystery of the central failures.

**Comment by tylerjereddy** [comment]
I debugged in a docker container and found that a segfault / core dump was occurring when using cKDTree with Cython 0.21.1 at the hash mentioned above for scipy, but Cython 0.18 seems to alleviate this issue so I've restarted the benchmarks with Cython 0.18 to see if the central missing benchmarks can finally be filled in completely; I'll update with a PR if there are improvements in the missing area.

Ideally we might have an automated way to find the appropriate matching Cython version -- for now, it is just clean builds in a docker container and iterating through Cython releases around the same time as the problematic commit hash until one seems to work.

**Comment by tylerjereddy** [comment]
There hasn't really been much more movement here -- the Figure has stayed the same without much additional comment in last 10 months, so I'll close this.

Another issue can be opened if there's a specific suggestion for that Figure that someone wants to implement.
