### ISSUE TITLE
repo access levels

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy-articles#2]
We might want to set a policy for read/write permissions to this repository. The simplest option seems to be to have the same access level for the main scipy/scipy code repo and this one.

**Comment by pv** [comment]
I would create a separate team for this repository.

**Comment by rgommers** [comment]
> We might want to set a policy for read/write permissions to this repository.

That is what I did I believe. Do you not have access?

> I would create a separate team for this repository.

Who'd be in it aside from ``core``?

**Comment by ev-br** [comment]
> That is what I did I believe. Do you not have access?

Not really. 
Something to do with being an owner or a collaborator on the organization?

**Comment by rgommers** [comment]
Ah, it said read access for the core team instead of write. Should be fixed now.
