### ISSUE TITLE
Additional Content Ideas

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy-articles#204]
Is it already decided that the current form should be the final one (besides minor improvements like typos / typography / minor image changes)?

If not, I would have two ideas:

* Displaying project structure (e.g. as nested boxes - the size could represent the number of code lines). This is done in the "Package organization" part already, but maybe an image could be more interesting.
* Dependency-Graph: Showing a couple of packages that use scipy. According to github, 116000 at the moment. The size of the other packages could depend on how many stars / forks / dependencies those have. The message this could convey could be "this is our eco-system and scipy is a fundamental part of it". Maybe this could even be connected with the project structure, showing how scipy enables others to do interesting stuff.

**Comment by rgommers** [comment]
> Is it already decided that the current form should be the final one

well we've submitted it and it's up on ArXiV, and it took us well over a year to get this out the door. so while improvements are nice, I expect at this point we will only do the minimal modifications needed based on reviewer feedback

> Dependency-Graph: Showing a couple of packages that use scipy.

you may like https://github.com/numpy/numpy.org/pull/23

**Comment by MartinThoma** [comment]
Ok. Thank you for the link and the answer!
