### ISSUE TITLE
Mix of mathematical objects and operations ?

### ISSUE THREAD

**Issue by FabricioS** [scipy/scipy-articles#205]
The second sentence of the introduction mentions "algorithms for optimization, integration, eigenproblem" (mathematical operations/processes) and "algebraic and differential equations". 
https://github.com/scipy/scipy-articles/blob/df63951af6a12a424734ce8e0163daff23779766/scipy-1.0/paper.tex#L120
The latter are not operations but objects upon which many different algorithms can operate (zero and fixed-points search, time or time-space integration, inverse problem to determine some optimal initial condition with respect to some criterion, etc...).

Even if the sentence is grammatically correct, shouldn't this be reworded ?

**Comment by mdhaber** [comment]
Normally I'm pretty picky about language precision, but I think I worked on this particular point before and made peace with it.

In the later part of the sentence, we consider "for" to mean:
"used as a function word to indicate the object or recipient of a perception, desire, or activity"

The algorithms act on these mathematical objects. 
Good enough?

**Comment by FabricioS** [comment]
OK,I think I can easily accept that.
Sorry for the noise

**Comment by mdhaber** [comment]
Not noise. Thanks for your thoughts.
