### ISSUE TITLE
Details on second occurrence of Pearu P.

### ISSUE THREAD

**Issue by FabricioS** [scipy/scipy-articles#206]
In https://github.com/scipy/scipy-articles/blob/df63951af6a12a424734ce8e0163daff23779766/scipy-1.0/paper.tex#L282, Pearu Petersen is described as a (former) "PhD student from Estonia". This mention might be more appropriate at the first occurrence of his name (two lines above).

**Comment by mdhaber** [comment]
For reference, it reads:
```
One of these packages, Multipack, was a set of
extension modules that wrapped Fortran and C libraries such as
ODEPACK, QUADPACK, and MINPACK, to solve and minimize nonlinear
equations, integrate differential equations, and fit splines (the
latter implemented by Pearu Peterson).  Robert Kern, then an
undergraduate student (and currently a SciPy core developer), provided
compilation instructions under Windows.
Around the same time, Pearu Peterson, a PhD student from Estonia,
released F2PY, a command line tool for binding Python and Fortran
codes, and wrote modules for linear algebra and interpolation.
```
I don't really like the parentheses in the first place, so I don't want to add more to them:
```
One of these packages, Multipack, was a set of
extension modules that wrapped Fortran and C libraries such as
ODEPACK, QUADPACK, and MINPACK, to solve and minimize nonlinear
equations, integrate differential equations, and fit splines (the
latter implemented by Pearu Peterson, a PhD student from Estonia.)
```
Can we just remove the bit in parentheses altogether?
Was Travis' _only_ help from Pearu on that one package, or were there others we're not mentioning? Can we justify drop this for consistency?

**Comment by FabricioS** [comment]
Hi,
thanks for considering the remark so quickly.
Seems OK to drop, at least from the perspective of equalize the level of details of authorship of the modules (I can't help with respect of the collaboration history on these packages)
