### ISSUE TITLE
Suggestions for further improvement

### ISSUE THREAD

**Issue by gertingold** [scipy/scipy-articles#209]
First of all, I like this paper a lot. It is really very interesting and very well written. Thanks to everybody who has contributed to it.

Apart from a few smaller fixes collected in #208, I have a few suggestions for (small) changes.

* On page 3, "to solve and minimize nonlinear equations" does not make sense to me because equations cannot be minimized. An option could be "to solve nonlinear equations and minimize nonlinear functions" even though I admit that the text becomes more clumsy.

* On page 4, it may not be clear to every reader what event is referred to in sentence 3 of the third paragraph in the section "SciPy matures". After all, the previous paragraph talks about documentation. How about replacing "The event" by "The SciPy conference"?

* On page 7, the last couple of lines in the first paragraph of the section "Project scope" seem broken. I do not think that a construction "while ... compared to ..." is possible. A simple solution could be to drop "while".

* In table 1, the only line in the table not referenced in the legend (apart from the references which are self-explained) is "Line search (LS) or trust-region (TR)". This line might deserve being mentioned in the legend.

**Comment by mdhaber** [comment]
Third bullet is being fixed in #211

**Comment by gertingold** [comment]
All points are addressed in #213.

**Comment by mdhaber** [comment]
When #213 is merged, this will close automatically. Thanks!
