### ISSUE TITLE
Multiple affiliations OK?

### ISSUE THREAD

**Issue by charris** [scipy/scipy-articles#210]
I noticed that some authors have multiple affiliations. If that is OK, I'd like to add
"Space Dynamics Laboratory, 1695 North Research Park Way, North Logan, UT 84341,  USA" to my affiliations.

For the rest, I think the `spatial` package could use a clearer summary in the project scope section. The whole sentence looks a bit off, actually

> and while sparse.csgraph or spatial offers basic tools for working with graphs and networks compared to a more specialized Python library likeNetworkX.

Might work better as

> and sparse.csgraph and spatial offer basic tools for working with graphs and networks compared to specialized libraries like NetworkX.

EDIT: As an historical note, I think SciPy 2008 was first where we actively sought presentations from outside the core developer community, there was a mailing list thread on the topic that I was involved in.

**Comment by mdhaber** [comment]
So both "Independent Researcher" and the Space Dynamics Laboratory? 
Added this to author spreadsheet.

**Comment by charris** [comment]
Great, thanks. I retired five years ago, but did some of my work on company time while employed. My excuse was that I needed things for my work, stable sorts and the constants package for instance, but SDL deserves some credit for not being too strict about how I spent my time.
