### ISSUE TITLE
References in Table 1

### ISSUE THREAD

**Issue by FabricioS** [scipy/scipy-articles#214]
The references in the last line of the Table 1 could be more nicely formatted using the \citen command from the cite package (already loaded by the wlscirep class currently used).

Direct use makes the table wider, and scaling could be appropriate
`\newcommand{\inlinecite}[1]{\footnotesize\citen{#1}}`
in header, and
`\inlinecite{nelder_simplex_1965, wright_direct_1996}`
at https://github.com/scipy/scipy-articles/blob/91afe6546f6b7caf37fe0f9fe8200a0ea3ee535f/scipy-1.0/scipy-optimize.tex#L73

**Comment by mdhaber** [comment]
Please open a PR so I can see the result

**Comment by ilayn** [comment]
You can also downscale it directly if that is the problem by the way. But it would make the table harder to read.

**Comment by mdhaber** [comment]
Closed by #215
