### ISSUE TITLE
`l-bfgs-b` supports bounds

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#216]
But this is not reflected in Table 1.

**Comment by antonior92** [comment]
That is absolutely true. I am sorry about that, there should be a tick there signaling that...

**Comment by antonior92** [comment]
I can fix that for the next version.

**Comment by mdhaber** [comment]
Great. PR welcome!

**Comment by antonior92** [comment]
PR #219

**Comment by mdhaber** [comment]
Closes by #219
