### ISSUE TITLE
ff84a98 pushed to main repo instead of fork

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#22]
I made two mistakes:

1. Forgot to branch before making changes/committing
2. Pushed to the main repo instead of my fork

I know how I could have recovered from the first mistake on its own, but now that I've pushed I am not sure what is best. Perhaps these changes are fine; I've only modified @antonior92's work and my own; I've asked him to review. In any case, I wanted everyone to know that the intent was to push to my repo and submit a PR; I'll do that next time.

**Comment by tylerjereddy** [comment]
Yeah, you can probably just work with @antonior92 to revert any changes, if any reverting is needed at all, by opening a new PR.

I think a slightly "wild west" approach to the paper was ok with Ralf & Pauli (within reason) if it helps move things forward, but yeah maybe don't want to push directly without a quick PR first as you say.

**Comment by mdhaber** [comment]
Ok, then we'll just say SLSQP is the only general method nlp method.

And thanks Tyler.
Glad it worked out.
