### ISSUE TITLE
Comment to Address: Scientific Software Funding

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#221]
Reviewer 1:
> Scientific software is depressingly underfunded. I imagine the economic cost of SciPy is in the tens (if not hundreds) of millions of dollars yet, as you mention, the actual direct financial contributions were a magnitude (or two) less. How did the SciPy community address this disparity? Are there lessons to be learned for the larger scientific community?

**Comment by rgommers** [comment]
Not sure that that reviewer was expecting a serious answer. I'd suggest reviewing the manuscript, but if it says something like "SciPy never received any funding" possibly adding something about GSoC and some in-kind support, then that should cover it. No major lessons to learn I'm afraid, other than patiently trying to recruit more volunteers.

**Comment by stefanv** [comment]
Agreed, the disparity mentioned has not been addressed yet.

**Comment by jarrodmillman** [comment]
I'll draft something tomorrow.
