### ISSUE TITLE
Underline Changes since initial submission

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#249]
Once #221 and #230 are closed, we should underline the changes since initial submission as requested:

> In order to facilitate review of the revised manuscript please provide a point-by-point rebuttal and **underline any additions to the text or areas with other significant changes**. Please ensure that the revised version is as concise as possible, and that it conforms to our format requirements (see http://www.nature.com/nmeth for our Guide to Authors). We shall return to the issue of format and presentation in the event that the manuscript is accepted for publication.

**Comment by jarrodmillman** [comment]
You may be familiar with this already, but just in case:
https://gitlab.com/git-latexdiff/git-latexdiff

**Comment by tylerjereddy** [comment]
Yeah, I think @ev-br also recommended latexdiff--this seems like a good companion to the rebuttal letter.

**Comment by mdhaber** [comment]
#251 addressed this
