### ISSUE TITLE
Resubmit to Nature Methods

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#254]
Suggested plan:

1. ~@tylerjereddy Merge #248 if it looks good (aside from not mentioning bibliography changes)~
2. @tylerjereddy Generate final latexdiff PDF
3. @mdhaber add bibliography changes to that PDF manually
4. @mdhaber @tylerjereddy @rgommers add signature to rebuttal letter
5. @tylerjereddy Resubmit

Does that sound good? @tylerjereddy that looks a little heavy on your end but I imagine #2 is easy since you've already been working with it.

**Comment by stefanv** [comment]
Thank you for all your work on this, @tylerjereddy and @mdhaber.

**Comment by tylerjereddy** [comment]
I'm adjusting the results from raw `latexdiff` on the two bbl files Matt linked in #248--the changes get commented out by default in many places because of the interference of bibtex commands. We'll see how far I get..

**Comment by mdhaber** [comment]
@tylerjereddy if it's not easy, I was just going to edit manually in Adobe Acrobat.

**Comment by tylerjereddy** [comment]
Ok, I made a repo [for additional latexdiff refinements](https://github.com/tylerjereddy/nmeth_resubmit) and the result is working pretty well for the references in a scripted manner now:
[diff-paper.pdf](https://github.com/scipy/scipy-articles/files/3633537/paper.pdf)

There are still opportunities to improve it, but time... does it look ok for refs? 

I patched up Table 1 to fit on the page, but at some cost--the diffs for the references at the bottom of that table were removed--I think those were nearly useless though, esp. with the overflow.

Things that could be better on the diff PDF include some extra whitespace (esp. around some optimize sections) & the references could still be a little more robust, but I think it is relatively clear even if some URLs don't get fully underlined, etc.

**Comment by mdhaber** [comment]
Wow, I think that's terrific. Not a big deal, but do you know why it missed the changes to the top author list but noted the changes to the consortium?

**Comment by charris** [comment]
The reviewer mail mentioned that corresponding authors need an ORCID id. Does that mean all of us mentioned as authors should go to the website and follow the link? Since that information is confidential to the core-dev list, it would be useful to post the procedure if it is required.

**Comment by tylerjereddy** [comment]
> The reviewer mail mentioned that corresponding authors need an ORCID id. Does that mean all of us mentioned as authors should go to the website and follow the link? Since that information is confidential to the core-dev list, it would be useful to post the procedure if it is required.

I think that's just Matt, Ralf & I (3 was the max allowed). I actually don't think even Matt & Ralf had a way to add their ORCID--perhaps I can ask politely if any others can have a way to add theirs.

**Comment by tylerjereddy** [comment]
> but do you know why it missed the changes to the top author list but noted the changes to the consortium?

Looking at the source, there are just plain DIF tags on the main author list because it is a command that happens before `\begin{document}`. There's a special preamble that gets added for latexdiff commands--I've tried shifting that prior to the title, but so far it doesn't like using latexdiff commands before the doc proper starts.

**Comment by tylerjereddy** [comment]
Maybe we could highlight those just in color or something manually? The repo is linked above if you want to see the plain linux diff tags on the main author list.

Alternatively, we may need to put the commands in a style file or something that is providing the title command, not sure.

**Comment by mdhaber** [comment]
I'll take a look, but IIRC I think somebody added an affiliation and consequently some numbers shuffled around. Since that's even less significant than the bibliography changes, I think we should just ignore it without mentioning it.

**Comment by tylerjereddy** [comment]
Ok, if you give me the green light I'll sign the letter & use the most recent PDF above

**Comment by mdhaber** [comment]
Yes, that was the only change to the top author list, so go for it.

**Comment by mdhaber** [comment]
Resubmitted by @tylerjereddy. Thanks!
