### ISSUE TITLE
Editorial Revision: Abstract Format

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#258]
From *Nature Methods* Editorial Team:

> Your abstract must be fewer than 80 words and should not include citations.

**Comment by mdhaber** [comment]
Simply cutting down to the most important 80 words:

> SciPy is an open source scientific computing library for the Python programming language. SciPy 1.0 was released in late 2017, about 16 years after the original release. SciPy has become a de facto standard for leveraging scientific algorithms in Python, with over 600 unique code contributors, thousands of dependent packages, 100000 dependent repositories, and millions of downloads per year. In this work, we provide an overview of the capabilities and development practices of SciPy and highlight some recent technical developments.

To avoid starting three of the four sentences with SciPy:

> SciPy is an open source scientific computing library for the Python programming language. Since its initial release in 2001, SciPy has become a de facto standard for leveraging scientific algorithms in Python, with over 600 unique code contributors, thousands of dependent packages, over 100000 dependent repositories, and millions of downloads per year. In this work, we provide an overview of the capabilities and development practices of SciPy 1.0 and highlight some recent technical developments.

**Comment by stefanv** [comment]
That reads well to me.

**Comment by tylerjereddy** [comment]
Ok, I added this shortened version of the abstract to the revised Word document in #256, so closing, thanks Matt.
