### ISSUE TITLE
Editorial Revision: Equations and Symbols

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#260]
From *Nature Methods* Editorial Team:

> Equations and symbols that will be set apart from the text must be in an editable format. Do not use embedded images for equations or symbols.

**Comment by mdhaber** [comment]
I think we can close this, right? In the current draft, the only equations are in the caption of the `minimize` table, and those are all editable. The table itself will by typeset in Word, and the vector versions of the figures meet this requirement.

**Comment by mdhaber** [comment]
All equations in the word document appear to be editable. No action needed except perhaps final check before submission.
