### ISSUE TITLE
Editorial Revision: Figure Legends

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#262]
From *Nature Methods* Editorial team:

> Figure legends should be concise. Begin with a brief title and then describe what is presented in the figure and detail all relevant statistical information. Avoid inappropriate methodological detail and any interpretation or discussion of figures.

**Comment by mdhaber** [comment]
We do have methodological detail and interpretation/discussion in figure captions, but I don't think it is "inappropriate". I really don't think this information belongs in the main text. I think we should ask Rita if she thinks the current caption detail is "inappropriate" and needs to be moved to the S.I.

**Comment by tylerjereddy** [comment]
From our Editorial Contact:

> I haven't looked closely at your figure legends yet. Please try to stick to describing what is in the figure and leaving further explanation in the relevant parts of the main text. When I line edit your paper I will make specific suggestions.

**Comment by mdhaber** [comment]
The timeline figure caption is fine. We added a bunch of that to satisfy a reviewer comment.

The code coverage figure would need to be trimmed quite a bit, as I think all of this (112 words) can be considered interpretation/discussion or methodological detail:
>  With the exception of the removal of ≈ 61000 lines of compiled code for SciPy v0.14, the volume of both compiled (C, C++, and Fortran) and Python code has increased between releases, as has the number of lines covered by unit tests. In SciPy v1.0.0, tests covered approximately 45% of 462574 lines of compiled code (many of which are automatically generated from Cython source), and nearly 87% of 106878 lines of Python code. Coverage analysis is performed automatically in our continuous integration suite using the pytest-cov and gcov libraries for Python and compiled code, respectively. The reconstitution of historical build and test environments for this figure was performed using a Docker-based approach.

Similarly, the benchmarking figure would need to be trimmed (52 words):
>  Substantial performance improvements were realized when cKDTree was fully Cythonized and again when it was rewritten in C++. The tree was generated without application of toroidal topology (boxsize=None), and tests were performed by Airspeed Velocity 0.4
using Python 2.7, NumPy 1.8.2, and Cython versions 0.27.3, 0.21.1, and 0.18 (for improved backward compatibility).

I don't think we want these changes in the arXiv revision.
