### ISSUE TITLE
Editorial Revision: Artwork Guidelines

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#263]
Attachment from *Nature Methods* Editorial team wrt formatting of images:

[NMETH-P39410A_Figure_Guidelines_1569514283_1.pdf](https://github.com/scipy/scipy-articles/files/3658908/NMETH-P39410A_Figure_Guidelines_1569514283_1.pdf)

**Comment by ilayn** [comment]
@mdhaber Should we assign ourselves to this ?

**Comment by mdhaber** [comment]
I'll take a more detailed look and let you know.

**Comment by tylerjereddy** [comment]
@mdhaber it looks like Figure 4 *might* already be in "vector" format (they accept PDF); I suppose it may need a slight resizing to match their guidelines for two-column width & height limits & possibly a font check to match their requirements

**Comment by tylerjereddy** [comment]
I imagine for Figure 3, it shouldn't be too hard to split that tikz code out of the manuscript & produce a standalone vector PDF as per their requirements.

**Comment by ilayn** [comment]
Figure 3 is already in vector format but sure we can separate the file out to a PDF. I think For fig 2 and 4, Matt has the inkscape files (and also TikZ version in #179). 

I think we need to change the caption of Fig. 1 to maybe a quote. Feels strange to have it as a figure.

**Comment by tylerjereddy** [comment]
> I think we need to change the caption of Fig. 1 to maybe a quote. Feels strange to have it as a figure.

Yeah, I think the specific request was to change it to a "Box" that wouldn't count against the word count total.

**Comment by mdhaber** [comment]
@ilayn I just created #263 for figures 2 and 4. If you could take care of 3 (please use Arial instead of Helvetica), I'd appreciate it. For consistency, could you use two of the colors from Figure 4?

It sounds like 1 needs to be changed in MS word?

**Comment by mdhaber** [comment]
I'd suggest that we don't change these in the LaTeX document; I would prefer the existing font for arXiv version 2.0.

**Comment by mdhaber** [comment]
@ilayn will you be able to provide the code coverage figure?

**Comment by ilayn** [comment]
@mdhaber I am a bit lost in the requirement between the Arxiv and the journal submission. Which one should I convert ? 

The fonts are taken from the surrounding TeX document hence I am not selecting any fonts.

**Comment by mdhaber** [comment]
Please see the guideline document in this issue's original post. For Nature Methods, we are submitting a Word document, not TeX. The figure is supposed to be a separate PDF. The figure should be 180mm wide, and text inside it should be Arial 7 pt.

**Comment by tylerjereddy** [comment]
@ilayn If you are swamped I can try to make the standalone PDF. We'll want to avoid long delays in resubmitting if possible. I suspect Matt & I still need to look over the paper carefully a little more given the conversion to Word, though I do hope we're converging on pretty decent quality soon.

**Comment by ilayn** [comment]
Just came home finally. Doing it now asap.

**Comment by ilayn** [comment]
This is the code coverage figure 
[codecov.pdf](https://github.com/scipy/scipy-articles/files/3693661/codecov.pdf)

created via : 

```latex
\documentclass{standalone}
\usepackage{fontspec}
\usepackage{pgfplotstable}
\setmainfont{Arial}
\begin{document}

\begin{tikzpicture}[]
\pgfplotstableread[column/ver/.style=string type]{
ver totpyline covpyline uncovpyline totcompline covcompline uncovcompline
v0.12.1 33844 25721 8123 273634  142290 131344
v0.13.3 36638 28944 7694 338926  172852 166074
v0.14.1 37301 30587 6714 277643  147151 130492
v0.15.1 38339 30288 8051 304898  158547 146351
v0.16.1 40094 32075 8019 322398  167647 154751
v0.17.1 42566 34478 8088 340903  170452 170451
v0.18.1 44711 36216 8495 353417  173174 180243
v0.19.1 43823 36373 7450 436900  200974 235926
v1.0.0 106878 92984 13894 462574 208158 254416
}\covtable
    \begin{axis}[
    width=180mm, % <== plot width
    height=7cm,
    enlargelimits=false,
    ymin=0,
    ymax=6e5,
    stack plots=y,%   
    area style,
    xtick=data,
    ytick={2e5,4e5,6e5},
    xticklabels from table={\covtable}{ver},
    scaled y ticks=false,
    yticklabel={\pgfmathparse{\tick}\pgfmathprintnumber[precision=1,fixed zerofill=false,assume math mode]{\pgfmathresult}},
    y tick label style={/pgf/number format/.cd, fixed, 1000 sep={}},
    legend entries={Compiled (covered),Compiled (uncovered),Python (covered),Python (uncovered)},
    legend style={draw=none,fill=none, cells={align=left},/tikz/every even column/.append style={column sep=3mm}},
    legend columns=-1,
    legend image code/.code={\fill[#1] (0cm,-0.1cm) rectangle (0.2cm,0.1cm);},
    ]
  \addplot+[fill=blue!50] table[x expr=\coordindex, y=covcompline] {\covtable} \closedcycle;
  \addplot+[fill=blue!10] table[x expr=\coordindex, y=uncovcompline] {\covtable} \closedcycle;
  \addplot+[fill=red!70] table[x expr=\coordindex, y=covpyline] {\covtable} \closedcycle;
  \addplot+[fill=red!30] table[x expr=\coordindex, y=uncovpyline] {\covtable} \closedcycle;
\end{axis}
\end{tikzpicture}

\end{document}
```

**Comment by ilayn** [comment]
Oops missed the font size req. please change the line of `setmainfont` to `\setmainfont[SizeFeatures={Size=7}]{Arial}` and compile with either Lua- or Xe-LaTeX.

**Comment by mdhaber** [comment]
@ilayn thanks for fixing the font.
What is the 23.3584 number at the bottom left?

**Comment by ilayn** [comment]
Ah my bad. I was testing something. Editing comment now.
