### ISSUE TITLE
Editorial Revision: General Formatting & Submission Checklists

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#264]
From *Nature Methods* Editorial team:

[NMETH-P39410A_Formatting_Guide_1569514283_2.docx](https://github.com/scipy/scipy-articles/files/3658930/NMETH-P39410A_Formatting_Guide_1569514283_2.docx)
[NMETH-P39410A_Publishing_Policy_WS_1569514283_3.docx](https://github.com/scipy/scipy-articles/files/3658932/NMETH-P39410A_Publishing_Policy_WS_1569514283_3.docx)

Some points for discussion based on initial skim of those docs:

- ~$395 USD / color figure: what are we going to do about this? should we try to ask for an exemption or discuss splitting those costs between some of our "grants", etc.?~
- ~looks like there's a requirement to cite grant numbers that provided funding--certainly funders like it when this is done as well--that said, I know there was an initial decision that this was impractical--what to do here?~

**Comment by stefanv** [comment]
We should ask the editor about the color figure cost, and whether it would apply to a collaboration such as ours.

**Comment by mdhaber** [comment]
> $395 USD / color figure

If all else fails, Tidelift money, right?

> looks like there's a requirement to cite grant numbers

I can ask Joe Harrington about the one(s) that sponsored the documentation project.

**Comment by ev-br** [comment]
>  cite grant numbers that provided funding--certainly funders like it when this is done as well--that said, I know there was an initial decision that this was impractical--what to do here?

That'll open the floodgates: every grad student was funded by some grant even when slacking off to work on scipy; most of these have expired, but everyone has a new one, and you need an acknowledgement to include a paper to the report...

**Comment by rgommers** [comment]
I'd say only grants where the grant proposal said that the funds were for work on SciPy would qualify, not just any grant that people who contributed to SciPy were supported by. 

I think the number of those grants was zero.

**Comment by mdhaber** [comment]
Yeah after re-reading the papers about the documentation project, even that money was not actually slated for SciPy. 

If someone can think of a grant pre-1.0 that was actually slated for SciPy work, please re-open.

**Comment by tylerjereddy** [comment]
We're definitely not done with the docs I linked above--reopening. I'll aim to pass along Stefan's point about the Figure cost & impracticality of Acknowledgements, but I don't see any reason to close this reminder to deal with that paperwork, etc.

**Comment by tylerjereddy** [comment]
For example, there are actual documents to sign--closing this would mean that we've signed / submitted them.

**Comment by mdhaber** [comment]
Oops.

**Comment by tylerjereddy** [comment]
From our Editorial contact:

> I will ask about the figure costs and if we can get them waived.

> I think your acknowledgements section is fine as is.

I'll update on the Figure costs when I hear more

**Comment by tylerjereddy** [comment]
Again from our Editorial Contact:

> Because your piece is a Perspective, we do not charge figure fees, so my apologies if we sent you a form about paying those--please disregard.

**Comment by mdhaber** [comment]
I think the Word Document now satisfies all the requirements in the Formatting Guide except:

- In Author List and Affiliations, we do not have an "Equal contributions statement". Presumably this is not needed as we have an Author Contributions Statement (which I've put after Acknowledgements according to the "Acknowledgements and Contributions" section).
- Author institutions might not satisfy all requirements. For instance, we abbreviated the names of US states.
- We don't have a "Corresponding Author Statement"

**Comment by mdhaber** [comment]
[Third Party Rights Table](https://www.dropbox.com/s/uclacgrbqr3s3ox/thirdpartyrights-table.doc?dl=0)

Did my best. If someone has better contact information for NumPy, scikit-learn, or Cython than I entered in the table, please let me know.

**Comment by mdhaber** [comment]
[Life Sciences Reporting Summary](https://www.dropbox.com/s/p8b9gfnh9f32tli/nr-reporting-summary.pdf?dl=0)
Tyler, can you review and add version numbers to the Software and Code section? (The instructions that appear if you remove all text from the box specify that version numbers should be included.)

**Comment by mdhaber** [comment]
Editorial Policy Checklist

@tylerjereddy I was looking at the requirements for the Data Availability Statement and I think we need to be more specific there about the location of raw data for figures. I added the location of data for Figures 2 and 3. (Note that the location of Figure 3 data is not cited / in the reference list.)

**Comment by mdhaber** [comment]
[Publishing Policy Worksheet](https://www.dropbox.com/s/lxnsxamn4vwqab1/NMETH-P39410A_Publishing_Policy_WS_1569514283_3.pdf?dl=0)

Requires manual signature. I pre-filled some information at the top and replaced the author list with the one from the manuscript. (There were no real changes; just formatting of special characters and  affiliation numbers as superscripts.)

**Comment by tylerjereddy** [comment]
It looks like most of that life science reporting document doesn't apply to us, but the software section obviously does. We used a few different things for collecting some metrics, so would be easy to forget something (there were a few versions of asv, the pypi parsing library, code cov repo...).

I don't think your link works if you added anything to the form. I can get a blank version from the original doc easily enough though.

**Comment by mdhaber** [comment]
I think the link is OK, but the Dropbox preview doesn't look right. The instructions for that form specify that it will only work with Acrobat / Acrobat Reader. Please try downloading it and opening it with Adobe.

**Comment by tylerjereddy** [comment]
[nr-reporting-summary.pdf](https://github.com/scipy/scipy-articles/files/3699101/nr-reporting-summary.pdf)

Hi Matt--thanks for filling in the reporting summary--I've attached above a version with a bit more version / branch details for what exactly was executed to generate the data.

Agreed on the other stuff we can't really fill in as it doesn't apply.

**Comment by tylerjereddy** [comment]
> Note that the location of Figure 3 data is not cited / in the reference list.

A compressed tarball with the raw data was merged into the articles repo here: https://github.com/scipy/scipy-articles/pull/144

Let me know if you want me to add an EndNote reference to that in the figure 3 caption. As it falls within the umbrella of the SciPy GitHub repo this may be less crucial as I think we mention that most material is available here.

**Comment by mdhaber** [comment]
Either way. I think I added a link to that in the changes I made last night to the Data Availability statement.

**Comment by tylerjereddy** [comment]
Are we looking pretty good for the submission paperwork then minus some signatures? I can try to make a push today at some point as it seems the manuscript is basically done & Figures maybe now too?

**Comment by mdhaber** [comment]
Yes. If you are willing to do the final submission, you should be the one to do the last check and sign off, and I think it's ready for that.

I've already looked through everything and I think we satisfy the requirements except a few that are noted in the checklist above.
