### ISSUE TITLE
Branch arXiv revision?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#266]
I'm wondering whether we want to create a branch for the arXiv revision? 
I don't think the remaining editorial revisions (or some of the cuts we did for the reviewers) are wanted in the arXiv version.

**Comment by tylerjereddy** [comment]
Isn't this the purpose of https://github.com/scipy/scipy-articles/pull/194?

I figured we'd want a separate branch so left that open--we can make decisions about what goes in the arxiv branch for revisions later & use latexdiff again to be sure if we want. It shouldn't be that hard to backport selectively.

That said, at least on my radar, this is lower priority than dealing with the NMETH stuff--I don't think there's a rush on arxiv version 2.

**Comment by mdhaber** [comment]
Oops. OK.
