### ISSUE TITLE
Editorial Revision: Remove Copyrighted Logos

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#268]
This may be our last blocker.

From the *Nature Methods* Editorial Team: 

> Figure 1 (the timeline) currently has copyrighted logos that we are not allowed to use. We request that you please upload a version of this timeline where the logos are replaced with plain text description.

cc @mdhaber @ilayn 

We did ask for clarification given that some of these seem to fall within fair use, but the publishing entity seems nervous about it.

**Comment by ilayn** [comment]
I don't find the logos too important for the storyline anyways. So fwiw, we can remove them which makes it easier to make the timeline.

**Comment by rgommers** [comment]
+1 for removing

**Comment by mdhaber** [comment]
Internet started working. See `scipy_timeline_NM2` files in #265.

**Comment by tylerjereddy** [comment]
Thanks Matt---I've uploaded the revised PDF version of that Figure along with the new copyright form. Hopefully we're in good shape now..

**Comment by tylerjereddy** [comment]
Should be done with this now, thanks.
