### ISSUE TITLE
Author Queries (AQs) for NMETH proofs

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#269]
I've addressed 32 out of the 42 explicit Author Queries (AQs) from the *Nature Methods* Editorial team with respect to our final article proofs. 

Some of the remaining queries will only make sense to the subset of authors currently accessing the proofs document online, but others require more general action/information that you may be able to help me address. I will list all 10 remaining queries below:

- [x] AQ1: "Affiliation 27 inserted and remaining affiliations renumbered manually; please check"
- [x] AQ2: "City and state are required for USA addresses; placeholders have been inserted for affiliation 62 (**Jacob Silterra**). Please provide the actual location information."
- [x] AQ3: "Placeholder “Madrid” inserted; please provide a city for affiliation 72 (**Juan Luis Cano Rodríguez**)"
- [x] AQ4: "Placeholder “London” inserted; please provide a city for affiliation 79 (**Maximilian Bolingbroke**)"
- [X] AQ5: "Please confirm or correct the city name inserted in affiliation 65, and 69."
  - 65: **Sydney Informatics Hub, The University of Sydney, Sydney, NSW, Australia**
  - 69: **Department of Electrical Engineering, Universidade Federal de Campina Grande, Campina Grande, PB, Brazil**
- [x] AQ6: "City, state/province (if US/Canada) and country are required to enable your article to be structured and typeset. Placeholders have been inserted for affiliation 10 (**David Cournapeau**). Please provide the actual location information."
- [x] AQ7: "Please check your article carefully, coordinate with any co-authors and enter all final edits clearly in the eproof, remembering to save frequently. Once corrections are submitted, we cannot routinely make further changes to the article."
- [x] AQ9: "Author surnames have been highlighted. Please check these carefully and adjust if the first name or surname is marked up incorrectly. Note that changes here will affect indexing of your article in public repositories such as PubMed. Also, carefully check the spelling and numbering of all author names and affiliations, and the corresponding email address(es)."
- [x] AQ17: "**Per policy, please provide a positive competing interests statement for all authors who are employed in industry: as a default, “X.Y. is employed by Z, etc.**"
- [x] AQ22: [NOTE: these numbers have changed since text is static but numbering is dynamic with edits]:
"Please add abstract or presentation titles for all conference proceedings references: 38-41, 50, 55, 74, 75, 85 and 141."

cc @rgommers @mdhaber @stefanv

**Comment by mdhaber** [comment]
@jsilter per AQ2 above, can you please provide your city and state?
@Juanlu001 per AQ3 above, can you please provide your city? Barcelona, according to GitHub?
@batterseapower per AQ4 above, can you please provide your city? Rugby, according to GitHub?
@jnothman can you confirm or correct your city name in AQ5 above? It looks like Sydney is correct, according to GitHub? Should we list Camperdown (per [Google Maps](https://www.google.com/maps/place/Camperdown+NSW+2006,+Australia/@-33.8881146,151.1824276,16z/data=!4m5!3m4!1s0x6b12b1d4c730e481:0xcc6f97113473bdbf!8m2!3d-33.8877655!4d151.1883894))?
@mirca can you confirm or correct your city name in AQ5 above? Hong Kong, according to GitHub?
@cournape @apbard @cancan101 @dlax @e-q @eamartin @gfyoung @niknow @njsmith @perryism @person142 @timcera @timleslie @tomspur @sjpet @josef.pkt @charris  @WarrenWeckesser @ilayn per AQ6 above, can you please provide your city, state/province, and country?
I'll send emails, too.

**Comment by jsilter** [comment]
Re AQ2: My location is Malden, Massachusetts, USA.
Re AQ17: I am currently employed at Thomson Reuters though that shouldn't create any competing interests at all.
-Jacob Silterra

**Comment by cancan101** [comment]
New York City, New York, USA

**Comment by jnothman** [comment]
> Syndney Informatics Hub, The University of Sydney, Sydney, NSW, Australia

Syndney -> Sydney

If it _must_ have a city, Camperdown NSW might be most correct

**Comment by mirca** [comment]
Thanks for the ping @mdhaber!
Re AQ5: city name is "Campina Grande", state id is "PB", country is "Brazil".
If possible, I would also like to add my new university affiliation: "The Hong Kong University of Science and Technology", location: "Hong Kong SAR China". Thanks!

**Comment by mdhaber** [comment]
@tylerjereddy 

> 33. Harrington, J. in Proceedings of the 7th Python in Science Conference (eds., G. Varoquaux, T. Vaught, & K. J. Millman) 33–35 (2008). 

The SciPy documentation project

> 34. van der Walt, S. in Proceedings of the 7th Python in Science Conference (eds., G. Varoquaux, T. Vaught, & K. J. Millman) 27–28 (2008). 

The SciPy documentation project (technical overview)

> 35. Harrington, J. & Goldsmith, D. in Proceedings of the 8th Python in Science Conference (eds., G. Varoquaux, S. van der Walt, & K. J. Millman) 84–87 (2009). 

Progress report: NumPy and SciPy documentation in 2009

>36. Pérez, F., Langtangen, H.P. & LeVeque, R. in SIAM Conference on Computational Science and Engineering, 42 (5) (2009). 

Python for scientific computing

> 45. Seabold, S. & Perktold, J. in Proceedings of the 9th {P}ython in Science Conference 57–61 (2010).

Statsmodels: Econometric and statistical modeling with Python

> 49. Hagberg, A.A., Schult, D.A. & Swart, P.J. in Proceedings of the 7th Python in Science Conference. (eds. Varoquaux, G., Vaught, T. & Millman, K. J.) 11–15 (2008).

Exploring network structure, dynamics, and function using NetworkX

> 66. Lam, S.K., Pitrou, A. & Seibert, S. in Proceedings of the Second Workshop on the LLVM Compiler Infrastructure in HPC 7:1–7:6 (ACM, 2015).

 Numba: A LLVM-based Python JIT compiler

> 67. Bolz, C.F., Cuni, A., Fijalkowski, M. & Rigo, A. in Proceedings of the 4th Workshop on the Implementation, Compilation, Optimization of Object-Oriented Languages and Programming Systems 18–25 (ACM, 2009).

 Tracing the meta-level: PyPy’s tracing JIT compiler.

> 77. Henriksen, I. (2015) in Proceedings of the 14th Python in Science Conference (SciPy 2015) 49–52 (eds. Huff, K. & Bergstra, J.).

 Circumventing the linker: Using SciPy’s BLAS and LAPACK within Cython

> 118. Abbasi, H. in Proceedings of the 17th Python in Science Conference. (eds., F. Akici, D. Lippa, D. Niederhut, & M. Pacer) 27–30.

Sparse: A more modern sparse array library

**Comment by andyfaff** [comment]
Would it be possible for me to look at the proof?

**Comment by josef-pkt** [comment]
my city, state/province, and country
Montreal, Quebec, Canada
no affiliation or employer

**Comment by eamartin** [comment]
Re AQ6:
Chicago, IL, USA

**Comment by charris** [comment]
Charles Harris
Logan, Utah, USA.

**Comment by ilayn** [comment]
Ilhan polat
Amsterdam, the Netherlands

**Comment by perryism** [comment]
Perry Lee
Daly City, CA, USA

**Comment by timcera** [comment]
Tim Cera
Gainesville, FL, USA

**Comment by apbard** [comment]
Alessandro Pietro Bardelli
Milan, Italy

**Comment by dlax** [comment]
Denis Laxalde
Toulouse, France

**Comment by astrojuanlu** [comment]
AQ3: Madrid, Spain.

**Comment by gfyoung** [comment]
@tylerjereddy : I just sent an email with the requested information.

**Comment by batterseapower** [comment]
AQ4: Rugby, United Kingdom

**Comment by tylerjereddy** [comment]
@andyfaff I've copied you on the email chain with Ralf & Matt---if other core devs want to see the proofs I can include them too.

**Comment by WarrenWeckesser** [comment]
I was unaffiliated when the paper was prepared, but my affiliation is now

    Berkeley Institute for Data Science
    UC Berkeley
    Berkeley, CA  USA

**Comment by tylerjereddy** [comment]
For AQ17 I made my life a little easier by using the main author list only for industry affiliations. After all, they don't list the affiliation numbers next to author names in the extended Contributor list in the proofs that can be edited.

I've checked off all the Author Queries now. I will probably submit in a few hours after looking through the proofs one more time tonight. SciPy core devs do have access to the proofs link if they want to communicate any final concerns.

**Comment by mdhaber** [comment]
@tylerjereddy Thanks I was just about to put that together, and I would have done the same thing!

**Comment by mdhaber** [comment]
@tylerjereddy Would you like me to double-check anything in particular? Let me know if there's anything you'd like a second set of eyes to go through.

Some things I noticed already:
Table 1 looks off in the proof. The top row needs to be shifted one column to the right.
Figure 2 still has that random number at the bottom left. @ilayn I see you fixed the comment in https://github.com/scipy/scipy-articles/issues/263 but did you happen to re-generate the pdf? _Update: Maybe we shouldn't re-submit the graphic. It looks like they have adjusted the colors and aspect ratio, so perhaps they can just remove the number?_

**Comment by tylerjereddy** [comment]
I'll try to add comments/notes about those things to be safe when I go through.

**Comment by tylerjereddy** [comment]
Ok, I read through the manuscript proof one more time, made a few more small adjustments, and submitted.

In theory, that should be the end of allowed corrections, so closing, thanks.
