### ISSUE TITLE
figure out the right wording for (sub)package & (sub)module)

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#47]
We now use subpackage, package, module and submodule very inconsistently in various parts of the paper. Let's go through once we have completed most/all sections and do this right.

**Comment by tylerjereddy** [comment]
Are we still worried about this? I think I've seem some changes related to this going in, and can't imagine it would be a serious point of consideration for not accepting the paper.

**Comment by mdhaber** [comment]
I tried to make this consistent in the "Package Organization" section (renamed from "Submodule Organization", I think):
Package - `scipy`
Subpackage - `scipy.cluster`
Module - `scipy.cluster.vq` 
Note that `scipy.sparse.linalg` and `scipy.sparse.csgraph` are not actually .py files, so perhaps it's not technically accurate to call them modules/submodule if "[A module is a file containing Python definitions and statements.](https://docs.python.org/3/tutorial/modules.html)"? Perhaps "subsubpackage" would be the better term.

I don't think I considered it in other sections, though. 
@rgommers if you think of it, please do consider it during your review. I agree that it's important to submit a polished paper. Each individual issue like this has a small chance of distracting a reviewer, but let's do our best minimize the number of small chances.

**Comment by rgommers** [comment]
> Note that scipy.sparse.linalg and scipy.sparse.csgraph are not actually .py files, so perhaps it's not technically accurate to call them modules/submodule ...

That is correct. In the SciPy API we aim to have only subpackages, and no submodules within that. Most things that look like a submodule are accidents of history and *not* public according to our API doc page (public functions/objects are available in the subpackage).

> Perhaps "subsubpackage" would be the better term.

I'd try to avoid having to use that word. Better not to have to use a term for a 3-level nesting at all by editing the text. If we have to, I'd prefer to prioritize readable English over correctness by just saying "subpackage".

**Comment by mdhaber** [comment]
OK. I will search for errant use of "module" and try to standardize "package"/"subpackage"
