### ISSUE TITLE
authorship for the JOSS draft paper

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy-articles#5]
Everyone who contributed to scipy releases 0.18.0 or 0.18.1 is invited to be a co-author on the draft paper, gh-4.

We follow the usual ICMJE criteria for authorship:
(http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html#two)

* Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; AND 
* Drafting the work or revising it critically for important intellectual content; AND
* Final approval of the version to be published; AND
* Agreement to be accountable for all aspects of the work in ensuring that questions related to the accuracy or integrity of any part of the work are appropriately investigated and resolved.

Here contributions are defined via the commit logs, and *substantial contributions* are defined broadly: anything bigger than a very simple one-line documentation fix is substantial.

Anyone who satisfies and is willing to accept these responsibilities and commitments is welcome to be an author on this publication. For this, please add your name and affiliation (and, optionally, an ORCID ID if you have it), either
*  as a pull request to gh-4, or
* as a comment to this issue.

In case of a dispute which cannot be resolved otherwise, the final decision is taken by the corresponding author on consultation with the core development team.

**Comment by rgommers** [comment]
Closing this, because we didn't finish the 0.18.x JOSS paper. Thanks for all the work you put into that one @ev-br!
