### ISSUE TITLE
Coverage plot dips

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#60]
The % [coverage plot from codecov](https://codecov.io/gh/scipy/scipy) has a bit of strange activity (dip / spike) near the start of the 6 month time period--would be helpful to at least briefly explain why this is in the associated Figure caption.

**Comment by ilayn** [comment]
Isn't it just because tests are possibly added after a delay?

**Comment by tylerjereddy** [comment]
Closing this issue -- there are certainly still areas of confusion around our coverage statistics, even after recent attempts to "manually" improve them have been merged. But at least we're not using that codecov plot anymore.

That said, even our development-based coverage data probably is a source of some debate, so not sure we're going to get this "perfect." We used the open source tools available for the analyses to the best of our abilities & that seems reasonable as a first pass for the data.

If reviewers or someone asks for refinement with a **specific** criterion they can open an issue / PR for that.
