### ISSUE TITLE
journal to submit 1.0 paper to

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#7]
Suggestions so far:

- PeerJ Computer Science (https://peerj.com/computer-science)
- Journal of Open Research Software (https://openresearchsoftware.metajnl.com/)

Other options? Preferences?

**Comment by andyfaff** [comment]
Just from the landing page it looks like the second of those two (JORS) would fit better. From a pragmatic point of view I'd prefer a journal that is going to be indexed, have an impact factor, and have stamina (not sure how long the journals have been going, would like something that will be around in a few years time).

**Comment by rgommers** [comment]
JORS seems to have the right mission, but on further inspection it looks a little problematic. The first paper about a familiar package I spotted was about `xarray`; it only has an abstract and the full paper html and pdf are missing: https://openresearchsoftware.metajnl.com/articles/10.5334/jors.148/. The same seems true of other (all?) papers. 

Then regarding types of papers, they have software and research papers. The latter are 4-6 pages, the former shorter - looks like halfway between a normal paper and the 3 paragraph format of JOSS.

The one redeeming feature is low processing charge for open access (100 pounds), but that shouldn't be the deciding factor.

**Comment by rgommers** [comment]
For some more options, I had a look at journals that papers about other core packages were published (see https://scipy.org/citing.html), and at the general journals list of https://software.ac.uk/which-journals-should-i-publish-my-software.

Main criteria:
- has to be open access
- should be a decent journal likely to stick around
- should allow using the length and structure we'd like

The most popular journal previously published in is [Computing in Science & Engineering](http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?reload=true&punumber=5992). It fails the open access criterion though, IEEE paywalls are awful.

[Research Ideas and Outcomes](https://riojournal.com/articles) seems to tick all the boxes, so is an option. Looks a bit random though.

[PeerJ Computer Science](https://peerj.com/computer-science/) ticks all the boxes as well, and looks much better. E.g. here is the SymPy article: https://peerj.com/articles/cs-103/.

**Comment by rgommers** [comment]
The one other one that looks reasonable is [SoftwareX](https://www.journals.elsevier.com/softwarex/), but despite my nationality I'm not a fan of Elsevier....

**Comment by antonior92** [comment]
Another open project that I follow, [Julia](https://julialang.org/), have published its correspondent paper in [SIAM review](https://www.siam.org/journals/sirev.php). Theirs papers is this [one](https://julialang.org/publications/julia-fresh-approach-BEKS.pdf)

It seems like a good journal but the open access fee is way more expensive than JORS ($2500). Nevertheless, I believe the Scipy paper may fit in the scope of the journal (applied mathematics and scientific computation) and it may worth considering it.

**Comment by rgommers** [comment]
Thanks @antonior92. That's a lot of money .... It could fit, but I don't see any other articles on open source software when I browse the latest issues. The Julia article is nice though.

**Comment by ilayn** [comment]
It's better to have a full open access paper such that people can also use it outside paywalls. You can make it free to read by paying but still lots of conditions apply.

**Comment by mdhaber** [comment]
@rgommers Re: JORS not all papers have missing PDFs but still that is not a good sign. Their website has other issues, which doesn't inspire confidence. It also seems like almost all of the articles are the short "Software Metapapers" you mentioned. Even though they offer full-length articles, we might want to pick a journal geared toward full-length articles if that's what we want to write.

I haven't seen any downsides to PeerJ CS yet. The papers vary considerably in length, too; that flexibility is nice to have.

**Comment by antonior92** [comment]
I agree with the arguments against choosing SIAM review. 

Anyway, I just though it was worth mentioning it.

**Comment by ev-br** [comment]
SIREV does look nice, however, the timeline of the Julia paper looks a bit extravagant:

> Received by the editors December 18, 2014; accepted for publication (in revised form) December
16, 2015; published electronically February 7, 2017

There are other SIAM journals, too, e.g. http://epubs.siam.org/journal/sjoce3 SIAM J on Scientific Computing. The price tag is the same for all SIAM journals.

Two things to consider w.r.t. publishing charges:

1. Is open access charge something we can apply to NUMFocus for?
2. Do we really need open access? In my corner of research, it's typical to send a paper to a usual (non-open access) journal and simultaneously to arxiv.org. When/if a paper's accepted, you update the arXiv listings with the full text and a journal-ref.

**Comment by rgommers** [comment]
> Is open access charge something we can apply to NUMFocus for?

Yes. It's not guaranteed that the funding for it will be granted, but the chances for partial or full support are pretty good I'd say.

> Do we really need open access? In my corner of research, it's typical to send a paper to a usual (non-open access) journal and simultaneously to arxiv.org. When/if a paper's accepted, you update the arXiv listings with the full text and a journal-ref.

arXiv is very useful, but to me not a full replacement for accessing the actual published paper. Also from a principled point of view I strongly prefer open access, both for my own research and (especially) for an open source project like SciPy. So if there's a good option for doing open access, I see no reason to consider anything else.

**Comment by rgommers** [comment]
Plos One is pretty good, probably the second best option I've seen. Compared to PeerJ CS: publication charges are higher ($1500), authorship policy is more restrictive, and website generally doesn't look as good.

**Comment by mdhaber** [comment]
PLoS One has a much longer history and very high eigenfactor, which is nice. 
Nature's Scientific Reports is a megajournal like PLoS One, but has a higher impact factor and is all open access. The downside might be that typically papers are "[no more than 11 typeset pages in length](https://www.nature.com/srep/publish/guidelines)" (although there is not a strict limit).

**Comment by rgommers** [comment]
I had a look at Scientific Reports. The topics they accept do not seem to include software. There's Scientific Data from Nature, but no software/tools/methods equivalent.

**Comment by mdhaber** [comment]
They do have a category for mathematics and computing,
https://www.nature.com/search?journal=srep&subject=mathematics-and-computing&page=2
but it is a small category in the scheme of things.

Still, here is a paper about a Mathematica tool from as recently as late
January:
https://www.nature.com/articles/s41598-017-18894-7

**Comment by larsoner** [comment]
+1 for Scientific Reports if possible

**Comment by antonior92** [comment]
+1 for Scientific Reports for me as well

**Comment by rgommers** [comment]
Okay, Scientific Reports is popular and it looks like we've converged on a rough outline of the paper at least. So how about I email someone from the editorial board? I'll do so in a couple of days unless I hear otherwise. If anyone knows a relevant person on the editorial board please let me know, otherwise I'll pick someone with "computational ..." in their affiliation.

**Comment by tylerjereddy** [comment]
@rgommers My colleague Syma Khalid is on the Scientific Reports Editorial Board. We worked in the same lab at Oxford. I've reviewed some papers for her / the journal. I could ask her informally for opinion + most appropriate person to contact for this particular paper & cc you?

**Comment by rgommers** [comment]
That sounds useful Tyler, always better if you know someone. Go for it!

**Comment by rgommers** [comment]
Okay, Scientific Reports is a go (at least according to Syma Khalid, after sharing paper scope with her)! It looks like the majority would prefer Scientific Reports over the alternatives, so I propose we go with that. If there are no major objections, I'll close this issue as resolved in a couple of days.

**Comment by mdhaber** [comment]
Terrific! +1

**Comment by rgommers** [comment]
Okay, decided - closing. Thanks for the input all. I'll send a PR with the SR template.
