### ISSUE TITLE
47% of (Python?) machine learning projects on GitHub import SciPy

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy-articles#88]
I think that belongs somewhere!
https://github.blog/2019-01-24-the-state-of-the-octoverse-machine-learning/
I'll submit a PR when I can, but it's fine if somebody beats me to it.

**Comment by stefanv** [comment]
On January 24, 2019 21:14:46 Matt Haberland <notifications@github.com> wrote:
> I think that belongs somewhere!
> https://github.blog/2019-01-24-the-state-of-the-octoverse-machine-learning/
That's great, definitely agree!
